src/main/default/objects/BotUpsertDataEvent__e/BotUpsertDataEvent__e.object-meta.xml
<CustomObject>
    <description>Needed to perform DML operations during a transaction that contains callouts to avoid issues with uncommited work pending</description>
    <label>Bot Upsert Data Event</label>
    <pluralLabel>Bot Upsert Data Events</pluralLabel>
</CustomObject>

src/main/default/objects/BotUpsertDataEvent__e/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <description>JSON serialized list of sObject records</description>
    <label>Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/BotUpsertDataEvent__e/fields/ExternalIdField__c.field-meta.xml
<CustomField>
    <fullName>ExternalIdField__c</fullName>
    <description>External id field name. Can be null</description>
    <label>External Id Field</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/main/default/classes/BotUtils.cls
public class BotUtils {
    private static final String URL_REGEX = '^(((https?:(?:\\/\\/)?)(?:[-;:&=\\+\\$,\\w]+@)?[A-Za-z0-9.-]+|(?:www.|[-;:&=\\+\\$,\\w]+@)[A-Za-z0-9.-]+)((?:\\/[\\+~%\\/.\\w-_]*)?\\??(?:[-\\+=&;%@.\\w_#]*)#?(?:[.\\!\\/\\w]*))?)$';
    private static final Integer EXTERNAL_ID_LENGTH = 40;

    private BotUtils() {}

    public static void saveAsync(List<SObject> records, String externalIdField) {
        if (!records.isEmpty()) {
            Eventbus.publish(
                new BotUpsertDataEvent__e(Data__c = JSON.serialize(records), ExternalIdField__c = externalIdField)
            );
        }
    }

    public static Boolean isUrl(String text) {
        return Pattern.matches(URL_REGEX, text);
    }

    public static String generateExternalId(String botTokenHash, String sourceExternalId) {
        if (sourceExternalId.contains(':')) {
            return sourceExternalId;
        }
        return (sourceExternalId + ':').rightPad(EXTERNAL_ID_LENGTH, botTokenHash);
    }

    public static Object createInstance(String typeName) {
        return createInstance(typeName, new Map<String, Object>());
    }

    public static Object createInstance(String typeName, Map<String, Object> params) {
        Type type = Type.forName(typeName);
        if (params.isEmpty()) {
            return type.newInstance();
        }
        return JSON.deserialize(JSON.serialize(params), type);
    }
}