src/main/default/objects/Chat__c/Chat__c.object-meta.xml
<CustomObject>
    <description>Chat where a bot is being used</description>
    <label>Chat</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Chat__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Chat id that is shared by a messenger</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/classes/models/ChatModel.cls
/**
 * @description The `Chat__c` sObject model
 */
global virtual class ChatModel {
    private final Chat__c entity;

    public ChatModel(Chat__c entity) {
        this.entity = entity;
    }

    /**
     * @description The `Chat__c` sObject `Id` field value
     */
    global transient Id id { get { return entity.Id; } }

    /**
     * @description The `Chat__c` sObject `Name` field value. The chat title
     */
    global transient String title { get { return entity.Name; } }

    /**
     * @description The `Chat__c` sObject `ExternalId__c` field value. The messanger's chat id
     */
    global transient String externalId { get { return entity.ExternalId__c; } }
}