src/main/default/objects/Chat__c/Chat__c.object-meta.xml
<CustomObject>
    <description>Chat where a bot is being used</description>
    <label>Chat</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Chat__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Chat id that is shared by a messenger</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/ChatMessage__c/ChatMessage__c.object-meta.xml
<CustomObject>
    <description>Message in the chat where a bot is involved</description>
    <label>Chat Message</label>
    <nameField>
        <displayFormat>MSG-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chat Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/ChatMessage__c/fields/Chat__c.field-meta.xml
<CustomField>
    <fullName>Chat__c</fullName>
    <description>Chat where the message is coming from</description>
    <label>Chat</label>
    <referenceTo>Chat__c</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/ChatMessage__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Message id that is shared by a messenger</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/ChatMessage__c/fields/MediaUrl__c.field-meta.xml
<CustomField>
    <fullName>MediaUrl__c</fullName>
    <description>The URL to the image or video sent in the message</description>
    <label>Media Url</label>
    <type>Url</type>
</CustomField>

src/main/default/objects/ChatMessage__c/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <description>The JSON object with message secondary parameters</description>
    <label>Parameters</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/ChatMessage__c/fields/SendDate__c.field-meta.xml
<CustomField>
    <fullName>SendDate__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>Date and time when the message has been sent in the chat</description>
    <label>Send Date</label>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/ChatMessage__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <description>The text of the message</description>
    <label>Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/ChatMessage__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The available message types for bot chat messages</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>Image</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>File</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/ChatMessage__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A chat user who sent the message. Can be null if the message was sent by a bot</description>
    <label>User</label>
    <referenceTo>ChatUser__c</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/ChatUser__c/ChatUser__c.object-meta.xml
<CustomObject>
    <description>A user participating in the chat where a bot is involved</description>
    <label>Chat User</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chat Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/ChatUser__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>User id that is shared by a messenger</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/classes/models/ChatMessageModel.cls
/**
 * @description The `ChatMessage__c` sObject model
 */
global virtual class ChatMessageModel {
    private final ChatMessage__c entity;

    public ChatMessageModel(ChatMessage__c entity) {
        this.entity = entity;
    }

    /**
     * @description The `ChatMessage__c` sObject `Id` field value
     */
    global transient Id id { get { return entity.Id; } }

    /**
     * @description The `ChatMessage__c` sObject `Text__c` field value
     */
    global transient String text { get { return entity.Text__c; } }

    /**
     * @description The `ChatMessage__c` sObject `MediaUrl__c` field value
     */
    global transient String mediaUrl { get { return entity.MediaUrl__c; } }

    /**
     * @description The instance of the <<ValueMap>> class based on `ChatMessage__c.Parameters__c` field value
     */
    global transient ValueMap parameters { get { return ValueMap.fromJson(entity.Parameters__c); } }

    /**
     * @description The instance of the <<BotMessageType>> enum based on `ChatMessage__c.Type__c` field value
     */
    global transient BotMessageType type { get { return BotMessageType.valueOf(entity.Type__c); } }

    /**
     * @description The `ChatMessage__c` sObject `SendDate__c` field value
     */
    global transient DateTime sendDate { get { return entity.SendDate__c; } }

    /**
     * @description The `ChatMessage__c` sObject `ExternalId__c` field value. The messanger's message id
     */
    global transient String externalId { get { return entity.ExternalId__c; } }

    /**
     * @description The instance of the <<ChatModel>> class based on `ChatMessage__c.Chat__c` field relationship. The chat where the message was sent
     */
    global transient ChatModel chat {
        get {
            if (chat == null && entity.getPopulatedFieldsAsMap().containsKey('Chat__c')) {
                chat = new ChatModel((Chat__c) entity.getSObject(ChatMessage__c.Chat__c));
            }
            return chat;
        }
        private set;
    }

    /**
     * @description The instance of the <<ChatUserModel>> class based on `ChatMessage__c.ChatUser__c` field relationship. The sender of the message
     */
    global transient ChatUserModel sender {
        get {
            if (sender == null && entity.getPopulatedFieldsAsMap().containsKey('User__c')) {
                sender = new ChatUserModel((ChatUser__c) entity.getSObject(ChatMessage__c.User__c));
            }
            return sender;
        }
        private set;
    }
}