src/main/default/objects/ChatUser__c/ChatUser__c.object-meta.xml
<CustomObject>
    <description>A user participating in the chat where a bot is involved</description>
    <label>Chat User</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chat Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/ChatUser__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>User id that is shared by a messenger</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/ChatUser__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>User&apos;s first name</description>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/ChatUser__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>User&apos;s last name</description>
    <label>Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/ChatUser__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>Username of a messenger user</description>
    <label>Username</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/classes/models/ChatUserModel.cls
/**
 * @description The `ChatUser__c` sObject model
 */
global virtual class ChatUserModel {
    private final ChatUser__c entity;

    public ChatUserModel(ChatUser__c entity) {
        this.entity = entity;
    }

    /**
     * @description The `ChatUser__c` sObject `Id` field value
     */
    global transient Id id { get { return entity.Id; } }

    /**
     * @description The `ChatUser__c` sObject `Username__c` field value
     */
    global transient String username { get { return entity.Username__c; } }

    /**
     * @description The `ChatUser__c` sObject `Name` field value
     */
    global transient String name { get { return entity.Name; } }

    /**
     * @description The `ChatUser__c` sObject `FirstName__c` field value
     */
    global transient String firstName { get { return entity.FirstName__c; } }

    /**
     * @description The `ChatUser__c` sObject `LastName__c` field value
     */
    global transient String lastName { get { return entity.LastName__c; } }

    /**
     * @description The `ChatUser__c` sObject `ExternalId__c` field value. The messanger's user id
     */
    global transient String externalId { get { return entity.ExternalId__c; } }
}