force-app/main/default/objects/Bot_Setting__mdt/Bot_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Uses to store information about settings for different bots</description>
    <label>Bot Setting</label>
    <pluralLabel>Bot Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Bot_Setting__mdt/fields/API_Url__c.field-meta.xml
<CustomField>
    <fullName>API_Url__c</fullName>
    <label>API Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/bot-services/BotSettingsService.cls
/**
 * Created by Ilya Matsuev on 8/26/2020.
 */

public with sharing class BotSettingsService {

    private static final Map<String, Bot_Setting__mdt> settingsBySystemNames = new Map<String, Bot_Setting__mdt>();


    public static Bot_Setting__mdt getBotSettings(String systemName) {
        Bot_Setting__mdt settings = null;
        if (settingsBySystemNames.containsKey(systemName)) {
            settings = settingsBySystemNames.get(systemName);
        } else {
            List<Bot_Setting__mdt> settingsList = [
                    SELECT DeveloperName, API_Url__c
                    FROM Bot_Setting__mdt
                    WHERE DeveloperName = :systemName
            ];
            if (!settingsList.isEmpty()) {
                settings = settingsList.get(0);
                settingsBySystemNames.put(systemName, settings);
            }
        }
        return settings;
    }
}