src/main/default/objects/Bot__c/Bot__c.object-meta.xml
<CustomObject>
    <description>Stores details of a bot instance</description>
    <label>Bot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Bot__c/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <description>Apex class that will be called if the bot receives an update</description>
    <externalId>true</externalId>
    <inlineHelpText>Apex class name</inlineHelpText>
    <label>Handler</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/Bot__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Unique bot token</description>
    <inlineHelpText>Unique bot token</inlineHelpText>
    <label>Token</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

src/main/default/objects/Bot__c/fields/TokenHash__c.field-meta.xml
<CustomField>
    <fullName>TokenHash__c</fullName>
    <description>Bot token hash value</description>
    <externalId>true</externalId>
    <inlineHelpText>Bot token hash value</inlineHelpText>
    <label>Token Hash</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Bot__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Bot type (e.g. Telegram, WhatsApp)</description>
    <inlineHelpText>Bot type (e.g. Telegram, WhatsApp)</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telegram</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Bot__c/fields/WebhookEvents__c.field-meta.xml
<CustomField>
    <fullName>WebhookEvents__c</fullName>
    <description>The webhook events to be handled by the bot. For example, if you select only &quot;Message&quot; then the bot will be able to handle only new incoming messages and nothing else</description>
    <inlineHelpText>The webhook events to be handled by the bot. For example, if you select only &quot;Message&quot; then the bot will be able to handle only new incoming messages and nothing else</inlineHelpText>
    <label>Webhook Events</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>callback_query</fullName>
                <label>Callback Query</label>
            </value>
            <value>
                <fullName>channel_post</fullName>
                <label>Channel Post</label>
            </value>
            <value>
                <fullName>chat_join_request</fullName>
                <label>Chat Join Request</label>
            </value>
            <value>
                <fullName>chat_member</fullName>
                <label>Chat Member</label>
            </value>
            <value>
                <fullName>chosen_inline_result</fullName>
                <label>Chosen Inline Result</label>
            </value>
            <value>
                <fullName>delivered</fullName>
                <label>Delivered</label>
            </value>
            <value>
                <fullName>edited_channel_post</fullName>
                <label>Edited Channel Post</label>
            </value>
            <value>
                <fullName>edited_message</fullName>
                <label>Edited Message</label>
            </value>
            <value>
                <fullName>failed</fullName>
                <label>Failed</label>
            </value>
            <value>
                <fullName>inline_query</fullName>
                <label>Inline Query</label>
            </value>
            <value>
                <fullName>message</fullName>
                <label>Message</label>
            </value>
            <value>
                <fullName>my_chat_member</fullName>
                <label>My Chat Member</label>
            </value>
            <value>
                <fullName>poll</fullName>
                <label>Poll</label>
            </value>
            <value>
                <fullName>poll_answer</fullName>
                <label>Poll Answer</label>
            </value>
            <value>
                <fullName>seen</fullName>
                <label>Seen</label>
            </value>
            <value>
                <fullName>subscribed</fullName>
                <label>Subscribed</label>
            </value>
            <value>
                <fullName>unsubscribed</fullName>
                <label>Unsubscribed</label>
            </value>
            <value>
                <fullName>webhook</fullName>
                <label>Webhook</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/BotUpdateEvent__e/BotUpdateEvent__e.object-meta.xml
<CustomObject>
    <description>The event is published when receiving a chatbot webhook update</description>
    <label>Bot Update Event</label>
    <pluralLabel>Bot Update Events</pluralLabel>
</CustomObject>

src/main/default/objects/BotUpdateEvent__e/fields/Bot__c.field-meta.xml
<CustomField>
    <fullName>Bot__c</fullName>
    <description>Serialized Bot__c sobject record</description>
    <label>Bot</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/BotUpdateEvent__e/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>Webhook request body containing information about the update</description>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/test/classes/ViberBotHandlerTest.cls
@IsTest(isParallel = true)
private class ViberBotHandlerTest {
    private static final BotType BOT_TYPE = BotType.Viber;

    @TestSetup
    private static void init() {
        BotSettingsProvider.mock();
    }

    @IsTest
    private static void onMessageReceived_shouldPopulateMessageReceivedEventFields() {
        BotPayload event = runTest(ViberUpdateEventType.Message);
        Assert.isInstanceOfType(event, ViberMessageReceivedEvent.class);

        ViberMessageReceivedEvent message = (ViberMessageReceivedEvent) event;
        Assert.areEqual('4912661846655238145', message.messageToken);
        Assert.areEqual(Date.newInstance(2022, 1, 1), message.timestamp.date());
        Assert.isNull(message.userId);
        assertUser(message.sender);
        assertMessage(message.message);
    }

    @IsTest
    private static void onMessageDelivered_shouldPopulateMessageEventFields() {
        BotPayload event = runTest(ViberUpdateEventType.Delivered);
        Assert.isInstanceOfType(event, ViberMessageEvent.class);

        ViberMessageEvent message = (ViberMessageEvent) event;
        Assert.areEqual('4912661846655238145', message.messageToken);
        Assert.areEqual(Date.newInstance(2022, 1, 1), message.timestamp.date());
        Assert.areEqual('01234567890A=', message.userId);
    }

    @IsTest
    private static void onMessageSeen_shouldPopulateMessageEventFields() {
        BotPayload event = runTest(ViberUpdateEventType.Seen);
        Assert.isInstanceOfType(event, ViberMessageEvent.class);

        ViberMessageEvent message = (ViberMessageEvent) event;
        Assert.areEqual('4912661846655238145', message.messageToken);
        Assert.areEqual(Date.newInstance(2022, 1, 1), message.timestamp.date());
        Assert.areEqual('01234567890A=', message.userId);
    }

    @IsTest
    private static void onMessageFailed_shouldPopulateMessageFailedEventFields() {
        BotPayload event = runTest(ViberUpdateEventType.Failed);
        Assert.isInstanceOfType(event, ViberMessageEvent.class);

        ViberMessageFailedEvent failure = (ViberMessageFailedEvent) event;
        Assert.areEqual('4912661846655238145', failure.messageToken);
        Assert.areEqual(Date.newInstance(2022, 1, 1), failure.timestamp.date());
        Assert.areEqual('Some error!', failure.description);
        Assert.areEqual('01234567890A=', failure.userId);
    }

    @IsTest
    private static void onUnsubscribe_shouldPopulateMessageEventFields() {
        BotPayload event = runTest(ViberUpdateEventType.Unsubscribed);
        Assert.isInstanceOfType(event, ViberMessageEvent.class);

        ViberMessageEvent message = (ViberMessageEvent) event;
        Assert.areEqual('4912661846655238145', message.messageToken);
        Assert.areEqual(Date.newInstance(2022, 1, 1), message.timestamp.date());
        Assert.areEqual('01234567890A=', message.userId);
    }

    @IsTest
    private static void onSubscribe_shouldPopulateSubscribedEventFields() {
        BotPayload event = runTest(ViberUpdateEventType.Subscribed);
        Assert.isInstanceOfType(event, ViberMessageEvent.class);

        ViberSubscribedEvent subscription = (ViberSubscribedEvent) event;
        Assert.areEqual('4912661846655238145', subscription.messageToken);
        Assert.areEqual(Date.newInstance(2022, 1, 1), subscription.timestamp.date());
        Assert.isNull(subscription.userId);
        assertUser(subscription.user);
    }

    private static BotPayload runTest(ViberUpdateEventType eventType) {
        Test.setMock(HttpCalloutMock.class, new ViberBotCalloutMock());

        BotModel bot = createBot();
        Test.startTest();
        EventBus.publish(new BotUpdateEvent__e(Bot__c = bot.toJson(), Payload__c = createPayload(eventType).toJson()));
        Test.getEventBus().deliver();
        Test.stopTest();

        Assert.isNotNull(ViberBotHandlerMock.lastEvent);
        return ViberBotHandlerMock.lastEvent;
    }

    private static BotModel createBot() {
        insert new Bot__c(
            Name = 'Test Bot',
            Type__c = BOT_TYPE.name(),
            WebhookEvents__c = 'message',
            Token__c = '74712731t723gjhbbfkwnkqwguqg17g2717283',
            Handler__c = 'ViberBotHandlerMock'
        );
        return new BotModel(
            [
                SELECT Name, Type__c, WebhookEvents__c, Handler__c, TokenHash__c
                FROM Bot__c
                WHERE Type__c = :BOT_TYPE.name()
                LIMIT 1
            ]
        );
    }

    private static BotJsonPayload createPayload(ViberUpdateEventType eventType) {
        BotJsonPayload eventPayload = new BotJsonPayload()
            .set('event', eventType.name())
            .set('timestamp', DateTime.newInstance(2022, 1, 1).getTime())
            .set('message_token', 4912661846655238145L);

        if (eventType == ViberUpdateEventType.Message) {
            eventPayload.set('message', createMessagePayload());
            eventPayload.set('sender', createUserPayload());
        } else if (
            eventType == ViberUpdateEventType.Delivered ||
            eventType == ViberUpdateEventType.Seen ||
            eventType == ViberUpdateEventType.Unsubscribed
        ) {
            eventPayload.set('user_id', '01234567890A=');
        } else if (eventType == ViberUpdateEventType.Failed) {
            eventPayload.set('user_id', '01234567890A=');
            eventPayload.set('desc', 'Some error!');
        } else if (eventType == ViberUpdateEventType.Subscribed) {
            eventPayload.set('user', createUserPayload());
        }
        return eventPayload;
    }

    private static BotJsonPayload createMessagePayload() {
        return new BotJsonPayload()
            .set('type', 'location')
            .set('text', 'Hello World!')
            .set('media', 'https://example.com/img.png')
            .set('location', new BotJsonPayload().set('lat', 50.76891).set('lon', 6.11499))
            .set('tracking_data', 'tracking');
    }

    private static BotJsonPayload createUserPayload() {
        return new BotJsonPayload()
            .set('id', '01234567890A=')
            .set('name', 'John McClane')
            .set('avatar', 'https://avatar.example.com')
            .set('country', 'UK')
            .set('language', 'en')
            .set('api_version', 1);
    }

    private static void assertMessage(ViberMessage message) {
        Assert.areEqual('location', message.type);
        Assert.areEqual('Hello World!', message.text);
        Assert.areEqual('https://example.com/img.png', message.media);
        Assert.areEqual('tracking', message.trackingData);
        Assert.isNull(message.fileName);
        Assert.isNull(message.fileSize);
        Assert.isNull(message.duration);
        Assert.isNull(message.stickerId);

        ViberMessage.Location location = message.location;
        Assert.areEqual(50.76891, location.latitude);
        Assert.areEqual(6.11499, location.longitude);

        ViberMessage.Contact contact = message.contact;
        Assert.isNull(contact.name);
        Assert.isNull(contact.phoneNumber);
        Assert.isNull(contact.avatar);
    }

    private static void assertUser(ViberUser user) {
        Assert.areEqual('01234567890A=', user.id);
        Assert.areEqual('John McClane', user.name);
        Assert.areEqual('https://avatar.example.com', user.avatar);
        Assert.areEqual('UK', user.country);
        Assert.areEqual('en', user.language);
        Assert.areEqual(1, user.apiVersion);
    }
}