src/main/default/objects/Bot__c/Bot__c.object-meta.xml
<CustomObject>
    <description>Stores details of a bot instance</description>
    <label>Bot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Bot__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Bot type (e.g. Telegram, WhatsApp)</description>
    <inlineHelpText>Bot type (e.g. Telegram, WhatsApp)</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telegram</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/BotSetting__mdt/BotSetting__mdt.object-meta.xml
<CustomObject>
    <description>Stores bot settings</description>
    <label>Bot Setting</label>
    <pluralLabel>Bot Settings</pluralLabel>
</CustomObject>

src/main/default/classes/bot-services/BotService.cls
public abstract class BotService {
    public Bot__c registration { get; protected set; }
    public BotSetting__mdt botSettings {
        get {
            return BotSettingsService.getBotSettings(registration.Type__c);
        }
    }

    public BotService(Bot__c registration) {
        this.registration = registration.clone(true, false, false, false);
    }

    protected abstract String getEndpoint(String method);

    protected virtual String getEndpoint(String method, Map<String, String> params) {
        return getEndpoint(method) + CalloutHelper.buildUrlParams(params);
    }
}