src/main/default/objects/Bot__c/Bot__c.object-meta.xml
<CustomObject>
    <description>Stores details of a bot instance</description>
    <label>Bot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/BotSetting__mdt/BotSetting__mdt.object-meta.xml
<CustomObject>
    <description>Stores bot settings</description>
    <label>Bot Setting</label>
    <pluralLabel>Bot Settings</pluralLabel>
</CustomObject>

src/main/default/objects/BotSetting__mdt/fields/BotUpdateEventEntity__c.field-meta.xml
<CustomField>
    <fullName>BotUpdateEventEntity__c</fullName>
    <description>The Apex class name that represents the payload entity received from the bot webhook</description>
    <inlineHelpText>The name of the class that implements IBotUpdateEventEntity interface</inlineHelpText>
    <label>Bot Update Event Entity</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/BotSetting__mdt/fields/EventTypesToIgnore__c.field-meta.xml
<CustomField>
    <fullName>EventTypesToIgnore__c</fullName>
    <description>The list of webhook event types separated by semicolons that have to be ignored during update handling</description>
    <inlineHelpText>The list of webhook event types separated by semicolons that have to be ignored during update handling</inlineHelpText>
    <label>Event Types To Ignore</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/BotUpdateEvent__e/BotUpdateEvent__e.object-meta.xml
<CustomObject>
    <description>The event is published when receiving a chatbot webhook update</description>
    <label>Bot Update Event</label>
    <pluralLabel>Bot Update Events</pluralLabel>
</CustomObject>

src/main/default/objects/BotUpdateEvent__e/fields/Bot__c.field-meta.xml
<CustomField>
    <fullName>Bot__c</fullName>
    <description>Serialized Bot__c sobject record</description>
    <label>Bot</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/BotUpdateEvent__e/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>Webhook request body containing information about the update</description>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Chat__c/Chat__c.object-meta.xml
<CustomObject>
    <description>Chat where a bot is being used</description>
    <label>Chat</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Chat__c/fields/Bot__c.field-meta.xml
<CustomField>
    <fullName>Bot__c</fullName>
    <description>A bot that is involved in the chat</description>
    <label>Bot</label>
    <referenceTo>Bot__c</referenceTo>
    <relationshipLabel>Chats</relationshipLabel>
    <relationshipName>Chats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Chat__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Chat id that is shared by a messenger</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/ChatMessage__c/ChatMessage__c.object-meta.xml
<CustomObject>
    <description>Message in the chat where a bot is involved</description>
    <label>Chat Message</label>
    <nameField>
        <displayFormat>MSG-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chat Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/ChatMessage__c/fields/Bot__c.field-meta.xml
<CustomField>
    <fullName>Bot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A bot that sent the message. Can be null if the message was sent by a chat user</description>
    <label>Bot</label>
    <referenceTo>Bot__c</referenceTo>
    <relationshipLabel>Chat Messages</relationshipLabel>
    <relationshipName>ChatMessages</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/ChatMessage__c/fields/Chat__c.field-meta.xml
<CustomField>
    <fullName>Chat__c</fullName>
    <description>Chat where the message is coming from</description>
    <label>Chat</label>
    <referenceTo>Chat__c</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/ChatMessage__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Message id that is shared by a messenger</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/ChatMessage__c/fields/SendDate__c.field-meta.xml
<CustomField>
    <fullName>SendDate__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>Date and time when the message has been sent in the chat</description>
    <label>Send Date</label>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/ChatMessage__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <description>The text of the message</description>
    <label>Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/ChatMessage__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A chat user who sent the message. Can be null if the message was sent by a bot</description>
    <label>User</label>
    <referenceTo>ChatUser__c</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/ChatUser__c/ChatUser__c.object-meta.xml
<CustomObject>
    <description>A user participating in the chat where a bot is involved</description>
    <label>Chat User</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chat Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/ChatUser__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>User id that is shared by a messenger</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/ChatUser__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>User&apos;s first name</description>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/ChatUser__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>User&apos;s last name</description>
    <label>Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/ChatUser__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>Username of a messenger user</description>
    <label>Username</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/classes/trigger-handlers/BotUpdateHandler.cls
public class BotUpdateHandler implements Triggers.IHandler {
    private final BotServiceFactory serviceFactory;

    public BotUpdateHandler() {
        this(new BotServiceFactory());
    }

    @TestVisible
    private BotUpdateHandler(BotServiceFactory serviceFactory) {
        this.serviceFactory = serviceFactory;
    }

    public void handle(Triggers.Context context) {
        List<BotContext> botContexts = createBotContexts((List<BotUpdateEvent__e>) context.props.newList);

        collectChatDetails(botContexts);

        for (BotContext botContext : botContexts) {
            handleUpdateEvent(botContext);
        }
    }

    private List<BotContext> createBotContexts(List<BotUpdateEvent__e> events) {
        // The loop is needed when a user sends several messages at the same time
        List<BotContext> botContexts = new List<BotContext>();
        for (BotUpdateEvent__e event : events) {
            BotModel bot = BotModel.fromJson(event.Bot__c);
            BotSetting__mdt settings = BotSettingsProvider.get(bot.type);

            IBotUpdateEventEntity updateEventEntity = (IBotUpdateEventEntity) ValueMap.fromJson(
                event.Payload__c,
                Type.forName(settings.BotUpdateEventEntity__c)
            );

            if (shouldHandleEvent(settings, updateEventEntity)) {
                botContexts.add(new BotContext(bot, new BotUpdateModel(updateEventEntity), serviceFactory));
            }
        }
        return botContexts;
    }

    private void collectChatDetails(List<BotContext> botContexts) {
        List<SObject> chatsDetails = new List<SObject>();
        for (BotContext context : botContexts) {
            for (SObject chatDetailEntry : getChatDetails(context)) {
                if (!chatsDetails.contains(chatDetailEntry)) {
                    chatsDetails.add(chatDetailEntry);
                }
            }
        }
        BotUtils.saveAsync(chatsDetails, 'ExternalId__c');
    }

    private void handleUpdateEvent(BotContext context) {
        try {
            context.bot.handler.handle(context);
        } catch (Exception error) {
            BotErrorLogger.log(context.bot.id, error);
        }
    }

    private Boolean shouldHandleEvent(BotSetting__mdt settings, IBotUpdateEventEntity updateEventEntity) {
        List<String> ignoreEventTypes = settings.EventTypesToIgnore__c?.split(';');
        return ignoreEventTypes == null || !ignoreEventTypes.contains(updateEventEntity.getType().name());
    }

    private List<SObject> getChatDetails(BotContext context) {
        Chat__c chat = getChat(context.bot, context.received.chat);
        ChatUser__c user = getChatUser(context.received.chat.sender);
        ChatMessage__c message = getChatMessage(chat.ExternalId__c, user.ExternalId__c, context.received.message);
        return new List<SObject> { chat, user, message };
    }

    private Chat__c getChat(BotModel bot, BotUpdateModel.ChatModel chat) {
        return new Chat__c(
            Name = chat.title,
            Bot__c = bot.id,
            ExternalId__c = BotUtils.generateExternalId(chat.id, bot.tokenHash)
        );
    }

    private ChatUser__c getChatUser(BotUpdateModel.UserModel user) {
        String userName = user.username;
        if (String.isNotBlank(user.firstName) || String.isNotBlank(user.lastName)) {
            userName = getValueOrEmptyString(user.firstName) + ' ' + getValueOrEmptyString(user.lastName);
        }
        return new ChatUser__c(
            Name = userName.trim(),
            FirstName__c = user.firstName,
            LastName__c = user.lastName,
            Username__c = user.username,
            ExternalId__c = user.id
        );
    }

    private ChatMessage__c getChatMessage(String chatId, String userId, BotUpdateModel.MessageModel message) {
        return new ChatMessage__c(
            Chat__r = new Chat__c(ExternalId__c = chatId),
            User__r = new ChatUser__c(ExternalId__c = userId),
            Text__c = message.text,
            SendDate__c = message.sentAt,
            ExternalId__c = BotUtils.generateExternalId(message.id, chatId)
        );
    }

    private String getValueOrEmptyString(String value) {
        return String.isBlank(value) ? '' : value;
    }
}