src/main/default/objects/Bot__c/Bot__c.object-meta.xml
<CustomObject>
    <description>Stores details of a bot instance</description>
    <label>Bot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Bot__c/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <description>Apex class that will be called if the bot receives an update</description>
    <externalId>true</externalId>
    <inlineHelpText>Apex class name</inlineHelpText>
    <label>Handler</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/Bot__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Unique bot token</description>
    <inlineHelpText>Unique bot token</inlineHelpText>
    <label>Token</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

src/main/default/objects/Bot__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Bot type (e.g. Telegram, WhatsApp)</description>
    <inlineHelpText>Bot type (e.g. Telegram, WhatsApp)</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telegram</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/BotSetting__mdt/BotSetting__mdt.object-meta.xml
<CustomObject>
    <description>Stores bot settings</description>
    <label>Bot Setting</label>
    <pluralLabel>Bot Settings</pluralLabel>
</CustomObject>

src/main/default/objects/BotSetting__mdt/fields/ApiUrl__c.field-meta.xml
<CustomField>
    <fullName>ApiUrl__c</fullName>
    <label>API Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

src/main/default/objects/BotUpsertDataEvent__e/BotUpsertDataEvent__e.object-meta.xml
<CustomObject>
    <description>Needed to perform DML operations during a transaction that contains callouts to avoid issues with uncommited work pending</description>
    <label>Bot Upsert Data Event</label>
    <pluralLabel>Bot Upsert Data Events</pluralLabel>
</CustomObject>

src/main/default/objects/BotUpsertDataEvent__e/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <description>JSON serialized list of sObject records</description>
    <label>Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/BotUpsertDataEvent__e/fields/ExternalIdField__c.field-meta.xml
<CustomField>
    <fullName>ExternalIdField__c</fullName>
    <description>External id field name. Can be null</description>
    <label>External Id Field</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Chat__c/Chat__c.object-meta.xml
<CustomObject>
    <description>Chat where a bot is being used</description>
    <label>Chat</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Chat__c/fields/Bot__c.field-meta.xml
<CustomField>
    <fullName>Bot__c</fullName>
    <description>A bot that is involved in the chat</description>
    <label>Bot</label>
    <referenceTo>Bot__c</referenceTo>
    <relationshipLabel>Chats</relationshipLabel>
    <relationshipName>Chats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Chat__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Chat id that is shared by a messenger</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/ChatMessage__c/ChatMessage__c.object-meta.xml
<CustomObject>
    <description>Message in the chat where a bot is involved</description>
    <label>Chat Message</label>
    <nameField>
        <displayFormat>MSG-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chat Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/ChatMessage__c/fields/Bot__c.field-meta.xml
<CustomField>
    <fullName>Bot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A bot that sent the message. Can be null if the message was sent by a chat user</description>
    <label>Bot</label>
    <referenceTo>Bot__c</referenceTo>
    <relationshipLabel>Chat Messages</relationshipLabel>
    <relationshipName>ChatMessages</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/ChatMessage__c/fields/Chat__c.field-meta.xml
<CustomField>
    <fullName>Chat__c</fullName>
    <description>Chat where the message is coming from</description>
    <label>Chat</label>
    <referenceTo>Chat__c</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/ChatMessage__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Message id that is shared by a messenger</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/ChatMessage__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <description>The text of the message</description>
    <label>Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/ChatMessage__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The available message types for bot chat messages</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>Image</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>File</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/ChatMessage__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A chat user who sent the message. Can be null if the message was sent by a bot</description>
    <label>User</label>
    <referenceTo>ChatUser__c</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/ChatUser__c/ChatUser__c.object-meta.xml
<CustomObject>
    <description>A user participating in the chat where a bot is involved</description>
    <label>Chat User</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chat Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/ChatUser__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>User id that is shared by a messenger</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/ChatUser__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>Username of a messenger user</description>
    <label>Username</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/test/classes/BotUpsertDataEventTriggerTest.cls
@IsTest(IsParallel=true)
private class BotUpsertDataEventTriggerTest {
    private static final String BOT_TYPE = BotType.Telegram.name();
    private static final String BOT_TOKEN = '74712731t723gjhbbfkwnkqwguqg17g2717283';
    private static final String BOT_HANDLER = 'BotHandlerMock';

    @TestSetup
    private static void init() {
        Test.setMock(
            HttpCalloutMock.class,
            new BotWebhookCalloutMock(BotType.valueOf(BOT_TYPE), TelegramBotMethod.SetWebhook.name())
        );
        BotType type = BotType.valueOf(BOT_TYPE);
        BotSettingsProvider.settings.put(
            type,
            new BotSetting__mdt(DeveloperName = type.name(), ApiUrl__c = 'https://bot-api.org/bot')
        );
        insert new Bot__c(Type__c = type.name(), Token__c = BOT_TOKEN, Handler__c = BOT_HANDLER);
    }

    @IsTest
    private static void handle_upsertMultipleRecords_shouldUpsertRecords() {
        Bot__c bot = [SELECT Id FROM Bot__c LIMIT 1];
        insert new Chat__c(Name = 'Chat1', Bot__c = bot.id, ExternalId__c = '1234');

        List<SObject> records = new List<SObject>{
            new Chat__c(Name = 'Chat11', Bot__c = bot.id, ExternalId__c = '1235'),
            new Chat__c(Name = 'Chat2', Bot__c = bot.id, ExternalId__c = '4321'),
            new ChatUser__c(Name = 'Test1', Username__c = 'username1', ExternalId__c = '1234'),
            new ChatMessage__c(
                Bot__c = bot.id,
                Chat__r = new Chat__c(ExternalId__c = '1234'),
                Text__c = 'test1',
                ExternalId__c = '0987'
            ),
            new ChatMessage__c(
                User__r = new ChatUser__c(ExternalId__c = '1234'),
                Chat__r = new Chat__c(ExternalId__c = '1234'),
                Text__c = 'test2',
                ExternalId__c = '5678'
            )
        };

        Test.startTest();
        Eventbus.publish(new BotUpsertDataEvent__e(Data__c = JSON.serialize(records)));
        Test.getEventBus().deliver();
        Test.stopTest();

        List<Chat__c> chats = [SELECT Id FROM Chat__c];
        List<ChatUser__c> users = [SELECT Id FROM ChatUser__c];
        List<ChatMessage__c> messages = [SELECT Id FROM ChatMessage__c];
        System.assertEquals(3, chats.size());
        System.assertEquals(1, users.size());
        System.assertEquals(2, messages.size());
    }

    @IsTest
    private static void handle_upsertMultipleRecordsWithExternalId_shouldUpsertRecords() {
        Bot__c bot = [SELECT Id FROM Bot__c LIMIT 1];
        insert new Chat__c(Name = 'Chat1', Bot__c = bot.id, ExternalId__c = '1234');

        List<SObject> records = new List<SObject>{
            new Chat__c(Name = 'Chat11', Bot__c = bot.id, ExternalId__c = '1234'),
            new Chat__c(Name = 'Chat2', Bot__c = bot.id, ExternalId__c = '4321'),
            new ChatUser__c(Name = 'Test1', Username__c = 'username1', ExternalId__c = '1234'),
            new ChatMessage__c(
                Bot__c = bot.id,
                Chat__r = new Chat__c(ExternalId__c = '1234'),
                Text__c = 'test1',
                ExternalId__c = '0987'
            ),
            new ChatMessage__c(
                User__r = new ChatUser__c(ExternalId__c = '1234'),
                Chat__r = new Chat__c(ExternalId__c = '1234'),
                Text__c = 'test2',
                ExternalId__c = '5678'
            )
        };

        Test.startTest();
        Eventbus.publish(
            new BotUpsertDataEvent__e(Data__c = JSON.serialize(records), ExternalIdField__c = 'ExternalId__c')
        );
        Test.getEventBus().deliver();
        Test.stopTest();

        List<Chat__c> chats = [SELECT Id FROM Chat__c];
        List<ChatUser__c> users = [SELECT Id FROM ChatUser__c];
        List<ChatMessage__c> messages = [SELECT Id FROM ChatMessage__c];
        System.assertEquals(2, chats.size());
        System.assertEquals(1, users.size());
        System.assertEquals(2, messages.size());
    }
}