src/main/default/objects/Bot__c/Bot__c.object-meta.xml
<CustomObject>
    <description>Stores details of a bot instance</description>
    <label>Bot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Bot__c/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <description>Apex class that will be called if the bot receives an update</description>
    <externalId>true</externalId>
    <inlineHelpText>Apex class name</inlineHelpText>
    <label>Handler</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/Bot__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Unique bot token</description>
    <inlineHelpText>Unique bot token</inlineHelpText>
    <label>Token</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

src/main/default/objects/Bot__c/fields/TokenHash__c.field-meta.xml
<CustomField>
    <fullName>TokenHash__c</fullName>
    <description>Bot token hash value</description>
    <externalId>true</externalId>
    <inlineHelpText>Bot token hash value</inlineHelpText>
    <label>Token Hash</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Bot__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Bot type (e.g. Telegram, WhatsApp)</description>
    <inlineHelpText>Bot type (e.g. Telegram, WhatsApp)</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telegram</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Bot__c/fields/WebhookEvents__c.field-meta.xml
<CustomField>
    <fullName>WebhookEvents__c</fullName>
    <description>The webhook events to be handled by the bot. For example, if you select only &quot;Message&quot; then the bot will be able to handle only new incoming messages and nothing else</description>
    <inlineHelpText>The webhook events to be handled by the bot. For example, if you select only &quot;Message&quot; then the bot will be able to handle only new incoming messages and nothing else</inlineHelpText>
    <label>Webhook Events</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>callback_query</fullName>
                <label>Callback Query</label>
            </value>
            <value>
                <fullName>channel_post</fullName>
                <label>Channel Post</label>
            </value>
            <value>
                <fullName>chat_join_request</fullName>
                <label>Chat Join Request</label>
            </value>
            <value>
                <fullName>chat_member</fullName>
                <label>Chat Member</label>
            </value>
            <value>
                <fullName>chosen_inline_result</fullName>
                <label>Chosen Inline Result</label>
            </value>
            <value>
                <fullName>delivered</fullName>
                <label>Delivered</label>
            </value>
            <value>
                <fullName>edited_channel_post</fullName>
                <label>Edited Channel Post</label>
            </value>
            <value>
                <fullName>edited_message</fullName>
                <label>Edited Message</label>
            </value>
            <value>
                <fullName>failed</fullName>
                <label>Failed</label>
            </value>
            <value>
                <fullName>inline_query</fullName>
                <label>Inline Query</label>
            </value>
            <value>
                <fullName>message</fullName>
                <label>Message</label>
            </value>
            <value>
                <fullName>my_chat_member</fullName>
                <label>My Chat Member</label>
            </value>
            <value>
                <fullName>poll</fullName>
                <label>Poll</label>
            </value>
            <value>
                <fullName>poll_answer</fullName>
                <label>Poll Answer</label>
            </value>
            <value>
                <fullName>seen</fullName>
                <label>Seen</label>
            </value>
            <value>
                <fullName>subscribed</fullName>
                <label>Subscribed</label>
            </value>
            <value>
                <fullName>unsubscribed</fullName>
                <label>Unsubscribed</label>
            </value>
            <value>
                <fullName>webhook</fullName>
                <label>Webhook</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/test/classes/BotResetWebhookActionControllerTest.cls
@IsTest(isParallel = true)
private class BotResetWebhookActionControllerTest {

    @IsTest
    private static void resetWebhook_withBotId_shouldSetWebhook() {
        BotResetWebhookActionController.serviceFactory = new BotServiceFactoryMock();
        Bot__c bot = createBot(BotType.Telegram);

        BotResetWebhookActionController.resetWebhook(bot.Id);

        Assert.areEqual(1, BotWebhookServiceMock.setWebhookCallCount);
        Assert.areEqual(0, BotWebhookServiceMock.unsetWebhookCallCount);
    }

    @IsTest
    private static void resetWebhook_withoutMatchingBot_shouldThrowException() {
        try {
            BotResetWebhookActionController.serviceFactory = new BotServiceFactoryMock();

            BotResetWebhookActionController.resetWebhook('some_random_id');
            Assert.fail('Exception should have been thrown');
        } catch (Exception ex) {
            Assert.isInstanceOfType(ex, AuraHandledException.class);
            Assert.areEqual(0, BotWebhookServiceMock.setWebhookCallCount);
            Assert.areEqual(0, BotWebhookServiceMock.unsetWebhookCallCount);
        }
    }

    private static Bot__c createBot(BotType type) {
        insert new Bot__c(
            Name = 'Test Bot',
            Type__c = type.name(),
            WebhookEvents__c = 'message',
            Token__c = '74712731t72317g2717283',
            Handler__c = 'BotHandlerMock'
        );
        return [SELECT Id, TokenHash__c FROM Bot__c WHERE Type__c = :type.name() LIMIT 1];
    }

    private class BotServiceFactoryMock extends BotServiceFactory {
        public override BotWebhookService createWebhookService(BotModel bot) {
            return new BotWebhookServiceMock();
        }
    }
}