src/main/default/objects/Bot__c/Bot__c.object-meta.xml
<CustomObject>
    <description>Stores details of a bot instance</description>
    <label>Bot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Bot__c/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <description>Apex class that will be called if the bot receives an update</description>
    <externalId>true</externalId>
    <inlineHelpText>Apex class name</inlineHelpText>
    <label>Handler</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/Bot__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Unique bot token</description>
    <inlineHelpText>Unique bot token</inlineHelpText>
    <label>Token</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

src/main/default/objects/Bot__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Bot type (e.g. Telegram, WhatsApp)</description>
    <inlineHelpText>Bot type (e.g. Telegram, WhatsApp)</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telegram</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/BotSetting__mdt/BotSetting__mdt.object-meta.xml
<CustomObject>
    <description>Stores bot settings</description>
    <label>Bot Setting</label>
    <pluralLabel>Bot Settings</pluralLabel>
</CustomObject>

src/main/default/objects/BotSetting__mdt/fields/ApiUrl__c.field-meta.xml
<CustomField>
    <fullName>ApiUrl__c</fullName>
    <label>API Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

src/main/default/objects/ChatUser__c/ChatUser__c.object-meta.xml
<CustomObject>
    <description>A user participating in the chat where a bot is involved</description>
    <label>Chat User</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chat Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/ChatUser__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>User id that is shared by a messenger</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/ChatUser__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>Username of a messenger user</description>
    <label>Username</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/test/classes/BotContextTest.cls
@IsTest(IsParallel=true)
private class BotContextTest {
    private static final BotType BOT_TYPE = BotType.Telegram;

    @TestSetup
    private static void init() {
        Test.setMock(HttpCalloutMock.class, new BotWebhookCalloutMock(BOT_TYPE, TelegramBotMethod.SetWebhook.name()));
        BotSettingsProvider.settings.put(
            BOT_TYPE,
            new BotSetting__mdt(DeveloperName = BOT_TYPE.name(), ApiUrl__c = 'https://bot-api.org/bot')
        );
        insert new Bot__c(
            Type__c = BOT_TYPE.name(),
            Token__c = '74712731t723gjhbbfkwnkqwguqg17g2717283',
            Handler__c = 'BotHandlerMock'
        );
    }

    @IsTest
    private static void getService_shouldCreateService() {
        Bot__c bot = [SELECT Type__c, Handler__c FROM Bot__c LIMIT 1];
        System.assert(createBotContext().getService(bot) != null);
    }

    @IsTest
    private static void save_noExternalId_shouldPublishUpsertEvent() {
        BotContext context = createBotContext();

        Test.startTest();
        context.save(new ChatUser__c(Name = 'Test', Username__c = 'test.name', ExternalId__c = '1234'));
        Test.stopTest();

        System.assertEquals(1, [SELECT Id FROM ChatUser__c].size());
    }

    @IsTest
    private static void send_replyWithMessage_shouldSendMessage() {
        BotContext context = createBotContext();

        context.reply.send('test message');

        System.assertEquals(1, BotServiceMock.outboundMessages.size());
        System.assertEquals(
            'test message',
            BotServiceMock.outboundMessages.get(String.valueOf(context.received.chat.id))
        );
    }

    @IsTest
    private static void received_telegramUpdateModelWithMessage_containsAllFields() {
        BotContext context = createBotContext();

        Map<String, Object> expectedPayload = new Map<String, Object>{
            'chat' => new Map<String, Object>{
                'firstName' => null,
                'id' => 876541222L,
                'lastName' => 'matsuev',
                'title' => null,
                'username' => 'ilya.matsuev'
            },
            'id' => 12312311L,
            'message' => new Map<String, Object>{
                'id' => 223123123L,
                'sentAt' => DateTime.newInstance(2022, 1, 1),
                'text' => 'Hello world!'
            },
            'user' => new Map<String, Object>{
                'firstName' => null,
                'id' => 876541222L,
                'lastName' => 'matsuev',
                'username' => 'ilya.matsuev'
            }
        };

        System.assertEquals(JSON.serialize(expectedPayload), JSON.serialize(context.received));
    }

    private static BotContext createBotContext() {
        Bot__c bot = [SELECT Type__c, Handler__c FROM Bot__c LIMIT 1];
        return new BotContext(
            bot,
            BotUpdateModel.fromPayload(createTelegramUpdateJson(), BOT_TYPE),
            new BotServiceFactoryMock()
        );
    }

    private static String createTelegramUpdateJson() {
        Map<String, Object> payload = new Map<String, Object>{
            'update_id' => 12312311L,
            'message' => new Map<String, Object>{
                'message_id' => 223123123L,
                'from' => new Map<String, Object>{
                    'id' => 876541222L,
                    'is_bot' => false,
                    'first_name' => null,
                    'last_name' => 'matsuev',
                    'username' => 'ilya.matsuev'
                },
                'date' => DateTime.newInstance(2022, 1, 1).getTime(),
                'chat' => new Map<String, Object>{
                    'id' => 876541222L,
                    'type' => 'private',
                    'title' => null,
                    'first_name' => null,
                    'last_name' => 'matsuev',
                    'username' => 'ilya.matsuev',
                    'description' => null
                },
                'text' => 'Hello world!'
            }
        };
        return JSON.serialize(payload);
    }

    private class BotServiceFactoryMock extends BotServiceFactory {
        public override BotService createBotService(Bot__c bot) {
            return new BotServiceMock(bot);
        }

        public override WebhookBotService createWebhookService(Bot__c bot) {
            return null;
        }
    }
}