src/main/default/objects/Bot__c/Bot__c.object-meta.xml
<CustomObject>
    <description>Stores details of a bot instance</description>
    <label>Bot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Bot__c/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <description>Apex class that will be called if the bot receives an update</description>
    <externalId>true</externalId>
    <inlineHelpText>Apex class name</inlineHelpText>
    <label>Handler</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/Bot__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Unique bot token</description>
    <inlineHelpText>Unique bot token</inlineHelpText>
    <label>Token</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

src/main/default/objects/Bot__c/fields/TokenHash__c.field-meta.xml
<CustomField>
    <fullName>TokenHash__c</fullName>
    <description>Bot token hash value</description>
    <externalId>true</externalId>
    <inlineHelpText>Bot token hash value</inlineHelpText>
    <label>Token Hash</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Bot__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Bot type (e.g. Telegram, WhatsApp)</description>
    <inlineHelpText>Bot type (e.g. Telegram, WhatsApp)</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telegram</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Bot__c/fields/WebhookEvents__c.field-meta.xml
<CustomField>
    <fullName>WebhookEvents__c</fullName>
    <description>The webhook events to be handled by the bot. For example, if you select only &quot;Message&quot; then the bot will be able to handle only new incoming messages and nothing else</description>
    <inlineHelpText>The webhook events to be handled by the bot. For example, if you select only &quot;Message&quot; then the bot will be able to handle only new incoming messages and nothing else</inlineHelpText>
    <label>Webhook Events</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>callback_query</fullName>
                <label>Callback Query</label>
            </value>
            <value>
                <fullName>channel_post</fullName>
                <label>Channel Post</label>
            </value>
            <value>
                <fullName>chat_join_request</fullName>
                <label>Chat Join Request</label>
            </value>
            <value>
                <fullName>chat_member</fullName>
                <label>Chat Member</label>
            </value>
            <value>
                <fullName>chosen_inline_result</fullName>
                <label>Chosen Inline Result</label>
            </value>
            <value>
                <fullName>delivered</fullName>
                <label>Delivered</label>
            </value>
            <value>
                <fullName>edited_channel_post</fullName>
                <label>Edited Channel Post</label>
            </value>
            <value>
                <fullName>edited_message</fullName>
                <label>Edited Message</label>
            </value>
            <value>
                <fullName>failed</fullName>
                <label>Failed</label>
            </value>
            <value>
                <fullName>inline_query</fullName>
                <label>Inline Query</label>
            </value>
            <value>
                <fullName>message</fullName>
                <label>Message</label>
            </value>
            <value>
                <fullName>my_chat_member</fullName>
                <label>My Chat Member</label>
            </value>
            <value>
                <fullName>poll</fullName>
                <label>Poll</label>
            </value>
            <value>
                <fullName>poll_answer</fullName>
                <label>Poll Answer</label>
            </value>
            <value>
                <fullName>seen</fullName>
                <label>Seen</label>
            </value>
            <value>
                <fullName>subscribed</fullName>
                <label>Subscribed</label>
            </value>
            <value>
                <fullName>unsubscribed</fullName>
                <label>Unsubscribed</label>
            </value>
            <value>
                <fullName>webhook</fullName>
                <label>Webhook</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/BotError__c/BotError__c.object-meta.xml
<CustomObject>
    <description>Stores errors happened when using the package</description>
    <label>Error</label>
    <nameField>
        <displayFormat>BE-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/BotError__c/fields/Bot__c.field-meta.xml
<CustomField>
    <fullName>Bot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A bot that produced the error</description>
    <label>Bot</label>
    <referenceTo>Bot__c</referenceTo>
    <relationshipLabel>Errors</relationshipLabel>
    <relationshipName>Errors</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/BotError__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>Additional information related to the error</description>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/BotUpdateEvent__e/BotUpdateEvent__e.object-meta.xml
<CustomObject>
    <description>The event is published when receiving a chatbot webhook update</description>
    <label>Bot Update Event</label>
    <pluralLabel>Bot Update Events</pluralLabel>
</CustomObject>

src/main/default/objects/BotUpdateEvent__e/fields/Bot__c.field-meta.xml
<CustomField>
    <fullName>Bot__c</fullName>
    <description>Serialized Bot__c sobject record</description>
    <label>Bot</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/BotUpdateEvent__e/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>Webhook request body containing information about the update</description>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Chat__c/Chat__c.object-meta.xml
<CustomObject>
    <description>Chat where a bot is being used</description>
    <label>Chat</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Chat__c/fields/Bot__c.field-meta.xml
<CustomField>
    <fullName>Bot__c</fullName>
    <description>A bot that is involved in the chat</description>
    <label>Bot</label>
    <referenceTo>Bot__c</referenceTo>
    <relationshipLabel>Chats</relationshipLabel>
    <relationshipName>Chats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Chat__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Chat id that is shared by a messenger</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/ChatMessage__c/ChatMessage__c.object-meta.xml
<CustomObject>
    <description>Message in the chat where a bot is involved</description>
    <label>Chat Message</label>
    <nameField>
        <displayFormat>MSG-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chat Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/ChatMessage__c/fields/Bot__c.field-meta.xml
<CustomField>
    <fullName>Bot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A bot that sent the message. Can be null if the message was sent by a chat user</description>
    <label>Bot</label>
    <referenceTo>Bot__c</referenceTo>
    <relationshipLabel>Chat Messages</relationshipLabel>
    <relationshipName>ChatMessages</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/ChatMessage__c/fields/Chat__c.field-meta.xml
<CustomField>
    <fullName>Chat__c</fullName>
    <description>Chat where the message is coming from</description>
    <label>Chat</label>
    <referenceTo>Chat__c</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/ChatMessage__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Message id that is shared by a messenger</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/ChatMessage__c/fields/SendDate__c.field-meta.xml
<CustomField>
    <fullName>SendDate__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>Date and time when the message has been sent in the chat</description>
    <label>Send Date</label>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/ChatMessage__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <description>The text of the message</description>
    <label>Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/ChatMessage__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The available message types for bot chat messages</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>Image</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>File</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/ChatMessage__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A chat user who sent the message. Can be null if the message was sent by a bot</description>
    <label>User</label>
    <referenceTo>ChatUser__c</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/ChatUser__c/ChatUser__c.object-meta.xml
<CustomObject>
    <description>A user participating in the chat where a bot is involved</description>
    <label>Chat User</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chat Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/ChatUser__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>User id that is shared by a messenger</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/ChatUser__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>User&apos;s first name</description>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/ChatUser__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>User&apos;s last name</description>
    <label>Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/ChatUser__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>Username of a messenger user</description>
    <label>Username</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/test/classes/BotUpdateEventTriggerTest.cls
@IsTest(isParallel = true)
private class BotUpdateEventTriggerTest {
    /**
     * Telegram tests
     */

    @IsTest
    private static void handle_telegramBotMessage_shouldHandleMessageAndInsertChatDetails() {
        Test.setMock(HttpCalloutMock.class, new TelegramBotCalloutMock());

        BotModel bot = createBot(BotType.Telegram);
        Test.startTest();
        EventBus.publish(new BotUpdateEvent__e(Bot__c = bot.toJson(), Payload__c = createTelegramPayload().toJson()));
        Test.getEventBus().deliver();
        Test.stopTest();

        List<Chat__c> chats = [SELECT Name, Bot__c, ExternalId__c FROM Chat__c];
        List<ChatUser__c> users = [SELECT Name, FirstName__c, LastName__c, Username__c, ExternalId__c FROM ChatUser__c];
        List<ChatMessage__c> messages = [
            SELECT Name, Text__c, User__c, Bot__c, Chat__c, ExternalId__c, SendDate__c
            FROM ChatMessage__c
        ];
        // Chat
        Assert.areEqual(1, chats.size());
        Assert.areEqual('Awesome chat', chats.get(0).Name);
        Assert.areEqual(bot.id, chats.get(0).Bot__c);
        Assert.areEqual('876541222:'.rightPad(40, bot.tokenHash), chats.get(0).ExternalId__c);
        // User
        Assert.areEqual(1, users.size());
        Assert.areEqual('matsuev', users.get(0).Name);
        Assert.isNull(users.get(0).FirstName__c);
        Assert.areEqual('matsuev', users.get(0).LastName__c);
        Assert.areEqual('ilyamatsuev', users.get(0).Username__c);
        Assert.areEqual('876541222', users.get(0).ExternalId__c);
        // Message
        Assert.areEqual(1, messages.size());
        Assert.areEqual('Hello world!', messages.get(0).Text__c);
        Assert.areEqual(users.get(0).Id, messages.get(0).User__c);
        Assert.areEqual(chats.get(0).Id, messages.get(0).Chat__c);
        Assert.isNull(messages.get(0).Bot__c);
        Assert.areEqual('223123123:876541222', messages.get(0).ExternalId__c);
        Assert.areEqual(Date.newInstance(2022, 1, 1), messages.get(0).SendDate__c.date());

        List<IBotContext> contexts = BotHandlerMock.executedContexts;
        Assert.areEqual(1, contexts.size());
        Assert.isInstanceOfType(contexts.get(0).getUpdateEvent(), TelegramUpdateEvent.class);

        IBotUpdateEvent updateEvent = contexts.get(0).getUpdateEvent();
        Assert.areEqual(TelegramUpdateEventType.Message, updateEvent.getType());

        IBotMessage messageUpdate = updateEvent.getMessage();

        Assert.areEqual('223123123', messageUpdate.getId());
        Assert.areEqual('Hello world!', messageUpdate.getText());
        Assert.isNull(messageUpdate.getMediaUrl());
        Assert.areEqual(BotMessageType.Text, messageUpdate.getType());
        Assert.isNotNull(messageUpdate.getParameters());
        Assert.areEqual(Date.newInstance(2022, 1, 1), messageUpdate.getSendDate().date());

        IBotChat chatUpdate = updateEvent.getChat();

        Assert.areEqual('876541222', chatUpdate.getId());
        Assert.areEqual('Awesome chat', chatUpdate.getTitle());

        IBotUser userUpdate = chatUpdate.getSender();

        Assert.areEqual('876541222', userUpdate.getId());
        Assert.isNull(userUpdate.getFirstName());
        Assert.areEqual('matsuev', userUpdate.getLastName());
        Assert.areEqual('ilyamatsuev', userUpdate.getUsername());
    }

    @IsTest
    private static void handle_telegramBotInlineQuery_shouldHandleInlineQueryAndInsertChatDetails() {
        Test.setMock(HttpCalloutMock.class, new TelegramBotCalloutMock());

        BotModel bot = createBot(BotType.Telegram);
        Test.startTest();
        EventBus.publish(
            new BotUpdateEvent__e(
                Bot__c = bot.toJson(),
                Payload__c = createTelegramPayload(TelegramUpdateEventType.InlineQuery).toJson()
            )
        );
        Test.getEventBus().deliver();
        Test.stopTest();

        List<Chat__c> chats = [SELECT Name, Bot__c, ExternalId__c FROM Chat__c];
        List<ChatUser__c> users = [SELECT Name, FirstName__c, LastName__c, Username__c, ExternalId__c FROM ChatUser__c];
        List<ChatMessage__c> messages = [SELECT Id FROM ChatMessage__c];
        // Chat
        Assert.areEqual(1, chats.size());
        Assert.areEqual('matsuev', chats.get(0).Name);
        Assert.areEqual(bot.id, chats.get(0).Bot__c);
        Assert.areEqual('876541222:'.rightPad(40, bot.tokenHash), chats.get(0).ExternalId__c);
        // User
        Assert.areEqual(1, users.size());
        Assert.areEqual('matsuev', users.get(0).Name);
        Assert.isNull(users.get(0).FirstName__c);
        Assert.areEqual('matsuev', users.get(0).LastName__c);
        Assert.areEqual('ilyamatsuev', users.get(0).Username__c);
        Assert.areEqual('876541222', users.get(0).ExternalId__c);
        // Message
        Assert.isTrue(messages.isEmpty());

        List<IBotContext> contexts = BotHandlerMock.executedContexts;
        Assert.areEqual(1, contexts.size());
        Assert.isInstanceOfType(contexts.get(0).getUpdateEvent(), TelegramUpdateEvent.class);

        IBotUpdateEvent updateEvent = contexts.get(0).getUpdateEvent();
        Assert.areEqual(TelegramUpdateEventType.InlineQuery, updateEvent.getType());
        Assert.isNull(updateEvent.getMessage());

        IBotChat chatUpdate = updateEvent.getChat();

        Assert.areEqual('876541222', chatUpdate.getId());
        Assert.areEqual('matsuev', chatUpdate.getTitle());

        IBotUser userUpdate = chatUpdate.getSender();

        Assert.areEqual('876541222', userUpdate.getId());
        Assert.isNull(userUpdate.getFirstName());
        Assert.areEqual('matsuev', userUpdate.getLastName());
        Assert.areEqual('ilyamatsuev', userUpdate.getUsername());
    }

    @IsTest
    private static void handle_telegramUpdateWithUnexpectedException_shouldThrowExceptionAndLogError() {
        Test.setMock(HttpCalloutMock.class, new TelegramBotCalloutMock());

        BotModel bot = createBot(BotType.Telegram);
        BotHandlerMock.throwError = true;
        Test.startTest();
        EventBus.publish(new BotUpdateEvent__e(Bot__c = bot.toJson(), Payload__c = createTelegramPayload().toJson()));
        Test.getEventBus().deliver();
        Test.stopTest();

        List<BotError__c> errors = [SELECT Id FROM BotError__c];
        List<Chat__c> chats = [SELECT Id FROM Chat__c];
        List<ChatUser__c> users = [SELECT Id FROM ChatUser__c];
        List<ChatMessage__c> messages = [SELECT Id FROM ChatMessage__c];

        Assert.areEqual(1, errors.size());
        Assert.areEqual(1, chats.size());
        Assert.areEqual(1, users.size());
        Assert.areEqual(1, messages.size());
    }

    /**
     * Viber tests
     */

    @IsTest
    private static void handle_viberBotMessage_shouldHandleMessageAndInsertChatDetails() {
        Test.setMock(HttpCalloutMock.class, new ViberBotCalloutMock());

        BotModel bot = createBot(BotType.Viber);
        Test.startTest();
        EventBus.publish(
            new BotUpdateEvent__e(
                Bot__c = bot.toJson(),
                Payload__c = createViberPayload(ViberUpdateEventType.Message).toJson()
            )
        );
        Test.getEventBus().deliver();
        Test.stopTest();

        List<Chat__c> chats = [SELECT Name, Bot__c, ExternalId__c FROM Chat__c];
        List<ChatUser__c> users = [SELECT Name, FirstName__c, LastName__c, Username__c, ExternalId__c FROM ChatUser__c];
        List<ChatMessage__c> messages = [
            SELECT Name, Text__c, User__c, Bot__c, Chat__c, ExternalId__c, SendDate__c
            FROM ChatMessage__c
        ];
        // Chat
        Assert.areEqual(1, chats.size());
        Assert.areEqual('John McClane', chats.get(0).Name);
        Assert.areEqual(bot.id, chats.get(0).Bot__c);
        Assert.areEqual('01234567890A=:'.rightPad(40, bot.tokenHash), chats.get(0).ExternalId__c);
        // User
        Assert.areEqual(1, users.size());
        Assert.areEqual('John McClane', users.get(0).Name);
        Assert.areEqual('John', users.get(0).FirstName__c);
        Assert.areEqual('McClane', users.get(0).LastName__c);
        Assert.areEqual('01234567890A=', users.get(0).Username__c);
        Assert.areEqual('01234567890A=', users.get(0).ExternalId__c);
        // Message
        Assert.areEqual(1, messages.size());
        Assert.areEqual('Hello world!', messages.get(0).Text__c);
        Assert.areEqual(users.get(0).Id, messages.get(0).User__c);
        Assert.areEqual(chats.get(0).Id, messages.get(0).Chat__c);
        Assert.isNull(messages.get(0).Bot__c);
        Assert.areEqual('4912661846655238145:01234567890A=', messages.get(0).ExternalId__c);
        Assert.areEqual(Date.newInstance(2022, 1, 1), messages.get(0).SendDate__c.date());

        List<IBotContext> contexts = BotHandlerMock.executedContexts;
        Assert.areEqual(1, contexts.size());
        Assert.isInstanceOfType(contexts.get(0).getUpdateEvent(), ViberUpdateEvent.class);

        IBotUpdateEvent updateEvent = contexts.get(0).getUpdateEvent();
        Assert.areEqual(ViberUpdateEventType.Message, updateEvent.getType());

        IBotMessage messageUpdate = updateEvent.getMessage();

        Assert.areEqual('4912661846655238145', messageUpdate.getId());
        Assert.areEqual('Hello world!', messageUpdate.getText());
        Assert.areEqual('https://example.com', messageUpdate.getMediaUrl());
        Assert.areEqual(BotMessageType.Text, messageUpdate.getType());
        Assert.isNotNull(messageUpdate.getParameters());
        Assert.areEqual(Date.newInstance(2022, 1, 1), messageUpdate.getSendDate().date());

        IBotChat chatUpdate = updateEvent.getChat();

        Assert.areEqual('01234567890A=', chatUpdate.getId());
        Assert.areEqual('John McClane', chatUpdate.getTitle());

        IBotUser userUpdate = chatUpdate.getSender();

        Assert.areEqual('01234567890A=', userUpdate.getId());
        Assert.areEqual('John', userUpdate.getFirstName());
        Assert.areEqual('McClane', userUpdate.getLastName());
        Assert.areEqual('01234567890A=', userUpdate.getUsername());
    }

    @IsTest
    private static void handle_viberUpdateWithUnexpectedException_shouldThrowExceptionAndLogError() {
        Test.setMock(HttpCalloutMock.class, new ViberBotCalloutMock());

        BotModel bot = createBot(BotType.Viber);
        BotHandlerMock.throwError = true;
        Test.startTest();
        EventBus.publish(
            new BotUpdateEvent__e(
                Bot__c = bot.toJson(),
                Payload__c = createViberPayload(ViberUpdateEventType.Message).toJson()
            )
        );
        Test.getEventBus().deliver();
        Test.stopTest();

        List<BotError__c> errors = [SELECT Id FROM BotError__c];
        List<Chat__c> chats = [SELECT Id FROM Chat__c];
        List<ChatUser__c> users = [SELECT Id FROM ChatUser__c];
        List<ChatMessage__c> messages = [SELECT Id FROM ChatMessage__c];

        Assert.areEqual(1, errors.size());
        Assert.areEqual(1, chats.size());
        Assert.areEqual(1, users.size());
        Assert.areEqual(1, messages.size());
    }

    @IsTest
    private static void handle_viberWebhookUrlCallback_shouldHandleUpdateAndIgnoreChatDetails() {
        Test.setMock(HttpCalloutMock.class, new ViberBotCalloutMock());

        BotModel bot = createBot(BotType.Viber);
        Test.startTest();
        EventBus.publish(
            new BotUpdateEvent__e(
                Bot__c = bot.toJson(),
                Payload__c = createViberPayload(ViberUpdateEventType.WebhookCallback).toJson()
            )
        );
        Test.getEventBus().deliver();
        Test.stopTest();

        List<BotError__c> errors = [SELECT Id FROM BotError__c];
        List<Chat__c> chats = [SELECT Id FROM Chat__c];
        List<ChatUser__c> users = [SELECT Id FROM ChatUser__c];
        List<ChatMessage__c> messages = [SELECT Id FROM ChatMessage__c];

        Assert.isTrue(errors.isEmpty());
        Assert.isTrue(chats.isEmpty());
        Assert.isTrue(users.isEmpty());
        Assert.isTrue(messages.isEmpty());

        List<IBotContext> contexts = BotHandlerMock.executedContexts;
        Assert.areEqual(1, contexts.size());
        Assert.isInstanceOfType(contexts.get(0).getUpdateEvent(), ViberUpdateEvent.class);

        IBotUpdateEvent updateEvent = contexts.get(0).getUpdateEvent();
        Assert.areEqual(ViberUpdateEventType.WebhookCallback, updateEvent.getType());

        Assert.isNull(updateEvent.getMessage());
        Assert.isNull(updateEvent.getChat());
    }

    private static BotModel createBot(BotType type) {
        insert new Bot__c(
            Name = type.name(),
            Type__c = type.name(),
            WebhookEvents__c = 'message',
            Token__c = '74712731t72317g2717283',
            Handler__c = 'BotHandlerMock'
        );
        return new BotModel(
            [
                SELECT Name, Type__c, WebhookEvents__c, Handler__c, Token__c, TokenHash__c
                FROM Bot__c
                WHERE Type__c = :type.name()
                LIMIT 1
            ]
        );
    }

    private static BotJsonPayload createTelegramPayload() {
        return createTelegramPayload(TelegramUpdateEventType.Message);
    }

    private static BotJsonPayload createTelegramPayload(TelegramUpdateEventType eventType) {
        BotJsonPayload eventPayload = new BotJsonPayload();
        if (eventType == TelegramUpdateEventType.Message || eventType == TelegramUpdateEventType.EditedMessage) {
            eventPayload
                .set('message_id', 223123123L)
                .set(
                    'from',
                    new BotJsonPayload()
                        .set('id', 876541222L)
                        .set('first_name', null)
                        .set('last_name', 'matsuev')
                        .set('username', 'ilyamatsuev')
                )
                .set('date', DateTime.newInstance(2022, 1, 1).getTime())
                .set(
                    'chat',
                    new BotJsonPayload()
                        .set('id', 876541222L)
                        .set('type', 'private')
                        .set('title', 'Awesome chat')
                        .set('first_name', null)
                        .set('last_name', 'matsuev')
                        .set('username', 'ilyamatsuev')
                        .set('description', null)
                )
                .set('text', 'Hello world!');
        } else if (eventType == TelegramUpdateEventType.InlineQuery) {
            eventPayload
                .set('id', '')
                .set(
                    'from',
                    new BotJsonPayload()
                        .set('id', 876541222L)
                        .set('first_name', null)
                        .set('last_name', 'matsuev')
                        .set('username', 'ilyamatsuev')
                )
                .set('query', 'abra bla bla');
        }
        return new BotJsonPayload().set('update_id', 12312311L).set(eventType.name(), eventPayload);
    }

    private static BotJsonPayload createViberPayload(ViberUpdateEventType eventType) {
        BotJsonPayload payload = new BotJsonPayload()
            .set('event', eventType.name())
            .set('timestamp', DateTime.newInstance(2022, 1, 1).getTime())
            .set('message_token', 4912661846655238145L);

        if (eventType == ViberUpdateEventType.Message) {
            payload
                .set(
                    'sender',
                    new BotJsonPayload()
                        .set('id', '01234567890A=')
                        .set('name', 'John McClane')
                        .set('avatar', 'http://avatar.example.com')
                        .set('country', 'UK')
                        .set('language', 'en')
                        .set('api_version', 1)
                )
                .set(
                    'message',
                    new BotJsonPayload()
                        .set('type', 'text')
                        .set('text', 'Hello world!')
                        .set('media', 'https://example.com')
                        .set('location', new BotJsonPayload().set('lat', 50.76891).set('lon', 6.11499))
                );
        }
        return payload;
    }
}