src/main/default/objects/Bot__c/Bot__c.object-meta.xml
<CustomObject>
    <description>Stores details of a bot instance</description>
    <label>Bot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Bot__c/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <description>Apex class that will be called if the bot receives an update</description>
    <externalId>true</externalId>
    <inlineHelpText>Apex class name</inlineHelpText>
    <label>Handler</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/Bot__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Unique bot token</description>
    <inlineHelpText>Unique bot token</inlineHelpText>
    <label>Token</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

src/main/default/objects/Bot__c/fields/TokenHash__c.field-meta.xml
<CustomField>
    <fullName>TokenHash__c</fullName>
    <description>Bot token hash value</description>
    <externalId>true</externalId>
    <inlineHelpText>Bot token hash value</inlineHelpText>
    <label>Token Hash</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Bot__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Bot type (e.g. Telegram, WhatsApp)</description>
    <inlineHelpText>Bot type (e.g. Telegram, WhatsApp)</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telegram</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/BotSetting__mdt/BotSetting__mdt.object-meta.xml
<CustomObject>
    <description>Stores bot settings</description>
    <label>Bot Setting</label>
    <pluralLabel>Bot Settings</pluralLabel>
</CustomObject>

src/main/default/objects/BotSetting__mdt/fields/ApiUrl__c.field-meta.xml
<CustomField>
    <fullName>ApiUrl__c</fullName>
    <label>API Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

src/test/classes/BotUpdateApiTest.cls
@IsTest(IsParallel = true)
private class BotUpdateApiTest {
    private static final String BOT_TYPE = BotType.Telegram.name();

    @TestSetup
    private static void init() {
        Test.setMock(
            HttpCalloutMock.class,
            new BotWebhookCalloutMock(BotType.valueOf(BOT_TYPE), TelegramBotMethod.SetWebhook)
        );
        BotSettingsProvider.settings.put(
            BotType.valueOf(BOT_TYPE),
            new BotSetting__mdt(DeveloperName = BOT_TYPE, ApiUrl__c = 'https://bot-api.org/bot')
        );
        insert new Bot__c(
            Type__c = BOT_TYPE,
            Token__c = '74712731t723gjhbbfkwnkqwguqg17g2717283',
            Handler__c = 'BotHandlerMock'
        );
    }

    @IsTest
    private static void post_telegramWebhookWithValidParams_shouldReturnOK() {
        Bot__c bot = [SELECT Id, TokenHash__c FROM Bot__c LIMIT 1];
        prepareRestContext('/' + BOT_TYPE + '/' + bot.Id, bot.TokenHash__c);

        BotUpdateApi.post();

        RestResponse response = RestContext.response;
        System.assertEquals('OK', response.responseBody.toString());
        System.assertEquals(200, response.statusCode);
    }

    @IsTest
    private static void post_telegramWebhookWithInvalidUrl_shouldReturnERROR() {
        Bot__c bot = [SELECT Id, TokenHash__c FROM Bot__c LIMIT 1];
        prepareRestContext('/' + bot.Id, bot.TokenHash__c);

        BotUpdateApi.post();

        RestResponse response = RestContext.response;
        System.assertEquals('ERROR', response.responseBody.toString());
        System.assertEquals(400, response.statusCode);
    }

    @IsTest
    private static void post_telegramWebhookWithInvalidSecret_shouldReturnERROR() {
        Bot__c bot = [SELECT Id, TokenHash__c FROM Bot__c LIMIT 1];
        prepareRestContext('/' + BOT_TYPE + '/' + bot.Id, 'dummy_hash');

        BotUpdateApi.post();

        RestResponse response = RestContext.response;
        System.assertEquals('ERROR', response.responseBody.toString());
        System.assertEquals(400, response.statusCode);
    }

    private static void prepareRestContext(String url, String secret) {
        RestRequest request = new RestRequest();
        request.httpMethod = 'POST';
        request.requestURI = 'services/apexrest/bots' + url;
        // We expect to receive the correct body from Messengers APIs therefore don't care about the content here
        request.requestBody = Blob.valueOf('{}');
        request.addHeader('Content-Type', 'application/json');
        request.addHeader('X-Telegram-Bot-Api-Secret-Token', secret);

        RestResponse response = new RestResponse();
        response.statusCode = 200;

        RestContext.request = request;
        RestContext.response = response;
    }

    public class TestBotHandler implements IBotHandler {
        public void handle(BotContext context) {}
    }
}