src/main/default/objects/Bot__c/Bot__c.object-meta.xml
<CustomObject>
    <description>Stores details of a bot instance</description>
    <label>Bot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Bot__c/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <description>Apex class that will be called if the bot receives an update</description>
    <externalId>true</externalId>
    <inlineHelpText>Apex class name</inlineHelpText>
    <label>Handler</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/classes/trigger-handlers/BotValidateHandlerTypeHandler.cls
public class BotValidateHandlerTypeHandler implements Triggers.IHandler {
    public void handle(Triggers.Context context) {
        for (Bot__c bot : (List<Bot__c>) context.props.newList) {
            Type handlerType = Type.forName(bot.Handler__c);
            // TODO: Also need to validate that if I use ViberBotHandler, then the bot type is selected as Viber. Same to Telegram
            if (handlerType == null || !IBotHandler.class.isAssignableFrom(handlerType)) {
                throw new BotValidationException(
                    'Bot handler does not exist or does not implement the IBotHandler interface: ' + bot.Handler__c
                );
            }
        }
    }
}