src/main/default/objects/Bot__c/Bot__c.object-meta.xml
<CustomObject>
    <description>Stores details of a bot instance</description>
    <label>Bot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Bot__c/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <description>Apex class that will be called if the bot receives an update</description>
    <externalId>true</externalId>
    <inlineHelpText>Apex class name</inlineHelpText>
    <label>Handler</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/Bot__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Unique bot token</description>
    <inlineHelpText>Unique bot token</inlineHelpText>
    <label>Token</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

src/main/default/objects/Bot__c/fields/TokenHash__c.field-meta.xml
<CustomField>
    <fullName>TokenHash__c</fullName>
    <description>Bot token hash value</description>
    <externalId>true</externalId>
    <inlineHelpText>Bot token hash value</inlineHelpText>
    <label>Token Hash</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Bot__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Bot type (e.g. Telegram, WhatsApp)</description>
    <inlineHelpText>Bot type (e.g. Telegram, WhatsApp)</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telegram</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Bot__c/fields/WebhookEvents__c.field-meta.xml
<CustomField>
    <fullName>WebhookEvents__c</fullName>
    <description>The webhook events to be handled by the bot. For example, if you select only &quot;Message&quot; then the bot will be able to handle only new incoming messages and nothing else</description>
    <inlineHelpText>The webhook events to be handled by the bot. For example, if you select only &quot;Message&quot; then the bot will be able to handle only new incoming messages and nothing else</inlineHelpText>
    <label>Webhook Events</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>callback_query</fullName>
                <label>Callback Query</label>
            </value>
            <value>
                <fullName>channel_post</fullName>
                <label>Channel Post</label>
            </value>
            <value>
                <fullName>chat_join_request</fullName>
                <label>Chat Join Request</label>
            </value>
            <value>
                <fullName>chat_member</fullName>
                <label>Chat Member</label>
            </value>
            <value>
                <fullName>chosen_inline_result</fullName>
                <label>Chosen Inline Result</label>
            </value>
            <value>
                <fullName>delivered</fullName>
                <label>Delivered</label>
            </value>
            <value>
                <fullName>edited_channel_post</fullName>
                <label>Edited Channel Post</label>
            </value>
            <value>
                <fullName>edited_message</fullName>
                <label>Edited Message</label>
            </value>
            <value>
                <fullName>failed</fullName>
                <label>Failed</label>
            </value>
            <value>
                <fullName>inline_query</fullName>
                <label>Inline Query</label>
            </value>
            <value>
                <fullName>message</fullName>
                <label>Message</label>
            </value>
            <value>
                <fullName>my_chat_member</fullName>
                <label>My Chat Member</label>
            </value>
            <value>
                <fullName>poll</fullName>
                <label>Poll</label>
            </value>
            <value>
                <fullName>poll_answer</fullName>
                <label>Poll Answer</label>
            </value>
            <value>
                <fullName>seen</fullName>
                <label>Seen</label>
            </value>
            <value>
                <fullName>subscribed</fullName>
                <label>Subscribed</label>
            </value>
            <value>
                <fullName>unsubscribed</fullName>
                <label>Unsubscribed</label>
            </value>
            <value>
                <fullName>webhook</fullName>
                <label>Webhook</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/BotError__c/BotError__c.object-meta.xml
<CustomObject>
    <description>Stores errors happened when using the package</description>
    <label>Error</label>
    <nameField>
        <displayFormat>BE-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/BotError__c/fields/Bot__c.field-meta.xml
<CustomField>
    <fullName>Bot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A bot that produced the error</description>
    <label>Bot</label>
    <referenceTo>Bot__c</referenceTo>
    <relationshipLabel>Errors</relationshipLabel>
    <relationshipName>Errors</relationshipName>
    <type>Lookup</type>
</CustomField>

src/test/classes/BotTriggerTest.cls
@IsTest(isParallel = true)
private class BotTriggerTest {
    private static final String BOT_TOKEN = '74712731t723gjhbbfkwnkqwguqg17g2717283';
    private static final String BOT_HANDLER = 'BotHandlerMock';

    /**
     * Telegram tests
     */

    @IsTest
    private static void insert_telegramWithCorrectData_shouldCreateBotAndSetWebhook() {
        Test.setMock(HttpCalloutMock.class, new TelegramBotCalloutMock());

        Test.startTest();
        insert createBot(BotType.Telegram, BOT_HANDLER);
        Test.stopTest();

        List<Bot__c> newBots = [
            SELECT Type__c, WebhookEvents__c, Handler__c, Token__c, TokenHash__c
            FROM Bot__c
        ];
        Assert.areEqual(1, newBots.size());
        Assert.isTrue(String.isNotBlank(newBots.get(0).TokenHash__c));
    }

    @IsTest
    private static void insert_telegramWithInvalidHandler_shouldThrowException() {
        Test.setMock(HttpCalloutMock.class, new TelegramBotCalloutMock());

        Exception error;
        Test.startTest();
        try {
            insert createBot(BotType.Telegram, 'BotTriggerTest.FakeBotHandler');
        } catch (Exception ex) {
            error = ex;
        }
        Test.stopTest();

        Assert.isTrue(error != null);
        Assert.isTrue(
            error.getMessage().contains('Bot handler does not exist or does not implement the IBotHandler interface')
        );
        List<BotError__c> errors = [SELECT Id FROM BotError__c];
        Assert.areEqual(0, errors.size());
    }

    @IsTest
    private static void insert_telegramWithBaseHandlerForDifferentType_shouldThrowException() {
        Test.setMock(HttpCalloutMock.class, new TelegramBotCalloutMock());

        Exception error;
        Test.startTest();
        try {
            insert createBot(BotType.Telegram, 'ViberBotHandlerMock');
        } catch (Exception ex) {
            error = ex;
        }
        Test.stopTest();

        Assert.isTrue(error != null);
        Assert.isTrue(error.getMessage().contains('Bot handler that extends ViberBotHandler must be of type Viber'));
        List<BotError__c> errors = [SELECT Id FROM BotError__c];
        Assert.areEqual(0, errors.size());
    }

    @IsTest
    private static void update_telegramWithNewWebhookEvents_shouldUpdateBotAndSetWebhook() {
        Test.setMock(HttpCalloutMock.class, new TelegramBotCalloutMock());

        Test.startTest();
        insert createBot(BotType.Telegram, BOT_HANDLER);
        Test.stopTest();

        Bot__c bot = [
            SELECT Type__c, WebhookEvents__c, Handler__c, Token__c, TokenHash__c
            FROM Bot__c
            LIMIT 1
        ];
        bot.WebhookEvents__c =
            TelegramUpdateEventType.Message.name() +
            ';' +
            TelegramUpdateEventType.EditedMessage.name();
        update bot;

        Bot__c updatedBot = [
            SELECT Type__c, WebhookEvents__c, Handler__c, Token__c, TokenHash__c
            FROM Bot__c
            LIMIT 1
        ];

        List<String> webhookEvents = updatedBot.WebhookEvents__c.split(';');
        Assert.areEqual(2, webhookEvents.size());
        Assert.isTrue(webhookEvents.contains('message'));
        Assert.isTrue(webhookEvents.contains('edited_message'));
    }

    @IsTest
    private static void delete_telegramWithCorrectData_shouldDeleteAndUnsetWebhook() {
        Test.setMock(HttpCalloutMock.class, new TelegramBotCalloutMock());

        Test.startTest();
        Bot__c bot = createBot(BotType.Telegram, BOT_HANDLER);
        insert bot;

        delete bot;
        Test.stopTest();
    }

    /**
     * Viber tests
     */

    @IsTest
    private static void insert_viberWithCorrectData_shouldCreateBotAndSetWebhook() {
        Test.setMock(HttpCalloutMock.class, new ViberBotCalloutMock());

        Test.startTest();
        insert createBot(BotType.Viber, BOT_HANDLER);
        Test.stopTest();

        List<Bot__c> newBots = [
            SELECT Type__c, WebhookEvents__c, Handler__c, Token__c, TokenHash__c
            FROM Bot__c
        ];
        Assert.areEqual(1, newBots.size());
        Assert.isTrue(String.isNotBlank(newBots.get(0).TokenHash__c));
    }

    @IsTest
    private static void insert_viberWithInvalidHandler_shouldThrowException() {
        Test.setMock(HttpCalloutMock.class, new ViberBotCalloutMock());

        Exception error;
        Test.startTest();
        try {
            insert createBot(BotType.Viber, 'BotTriggerTest.FakeBotHandler');
        } catch (Exception ex) {
            error = ex;
        }
        Test.stopTest();

        Assert.isTrue(error != null);
        Assert.isTrue(
            error.getMessage().contains('Bot handler does not exist or does not implement the IBotHandler interface')
        );
        List<BotError__c> errors = [SELECT Id FROM BotError__c];
        Assert.areEqual(0, errors.size());
    }

    @IsTest
    private static void delete_viberWithCorrectData_shouldDeleteAndUnsetWebhook() {
        Test.setMock(HttpCalloutMock.class, new ViberBotCalloutMock());

        Test.startTest();
        Bot__c bot = createBot(BotType.Viber, BOT_HANDLER);
        insert bot;

        delete bot;
        Test.stopTest();
    }

    private static Bot__c createBot(BotType type, String handlerName) {
        return new Bot__c(
            Type__c = type.name(),
            WebhookEvents__c = 'message',
            Token__c = BOT_TOKEN,
            Handler__c = handlerName
        );
    }
}