src/main/default/objects/Bot__c/Bot__c.object-meta.xml
<CustomObject>
    <description>Stores details of a bot instance</description>
    <label>Bot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/BotError__c/BotError__c.object-meta.xml
<CustomObject>
    <description>Stores errors happened when using the package</description>
    <label>Error</label>
    <nameField>
        <displayFormat>BE-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/BotError__c/fields/Bot__c.field-meta.xml
<CustomField>
    <fullName>Bot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A bot that produced the error</description>
    <label>Bot</label>
    <referenceTo>Bot__c</referenceTo>
    <relationshipLabel>Errors</relationshipLabel>
    <relationshipName>Errors</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/BotError__c/fields/ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>ExceptionType__c</fullName>
    <description>Apex type of the thrown exception</description>
    <label>Exception Type</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/BotError__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Error or exception full message</description>
    <label>Message</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/BotError__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>Stack trace of the error/exception</description>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/classes/utils/BotErrorLogger.cls
public class BotErrorLogger implements Triggers.IErrorHandler {
    public void handle(Triggers.Context context, Exception error) {
        log(error);
    }

    public static void log(Exception error) {
        log(null, error);
    }

    public static void log(Id botId, Exception error) {
        BotError__c botError = new BotError__c(
            Bot__c = botId,
            Message__c = error.getMessage(),
            ExceptionType__c = error.getTypeName(),
            StackTrace__c = error.getStackTraceString()
        );
        BotUtils.saveAsync(new List<SObject>{ botError }, null);
    }
}