src/main/default/objects/Bot__c/Bot__c.object-meta.xml
<CustomObject>
    <description>Stores details of a bot instance</description>
    <label>Bot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Bot__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Unique bot token</description>
    <inlineHelpText>Unique bot token</inlineHelpText>
    <label>Token</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

src/main/default/objects/Bot__c/fields/TokenHash__c.field-meta.xml
<CustomField>
    <fullName>TokenHash__c</fullName>
    <description>Bot token hash value</description>
    <externalId>true</externalId>
    <inlineHelpText>Bot token hash value</inlineHelpText>
    <label>Token Hash</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/classes/trigger-handlers/BotPopulateTokenHashHandler.cls
public class BotPopulateTokenHashHandler implements Triggers.IHandler {
    public static final String HASH_ALGORITHM = 'SHA-256';

    public void handle(Triggers.Context context) {
        for (Bot__c bot : (List<Bot__c>) context.props.newList) {
            Bot__c oldBot = (Bot__c) context.props.oldMap?.get(bot.Id);
            if (isTokenChanged(bot, oldBot)) {
                bot.TokenHash__c = generateTokenHash(bot.Token__c);
            }
        }
    }

    private Boolean isTokenChanged(Bot__c bot, Bot__c oldBot) {
        return String.isBlank(bot.TokenHash__c) || oldBot == null || bot.Token__c != oldBot.Token__c;
    }

    private String generateTokenHash(String token) {
        return EncodingUtil.convertToHex(Crypto.generateDigest(HASH_ALGORITHM, Blob.valueOf(token)));
    }
}