src/main/default/objects/Bot__c/Bot__c.object-meta.xml
<CustomObject>
    <description>Stores details of a bot instance</description>
    <label>Bot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Bot__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Unique bot token</description>
    <inlineHelpText>Unique bot token</inlineHelpText>
    <label>Token</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

src/main/default/objects/Bot__c/fields/TokenHash__c.field-meta.xml
<CustomField>
    <fullName>TokenHash__c</fullName>
    <description>Bot token hash value</description>
    <externalId>true</externalId>
    <inlineHelpText>Bot token hash value</inlineHelpText>
    <label>Token Hash</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/viber/classes/services/ViberWebhookBotService.cls
public class ViberWebhookBotService extends WebhookBotService {
    public ViberWebhookBotService(Bot__c bot) {
        super(bot);
    }

    public override void setWebhook() {
        ValueMap payload = new ValueMap()
            .set('url', webhookUrl + '/' + bot.TokenHash__c)
            .set('send_name', true)
            .set('send_photo', true)
            .set(
                'event_types',
                new List<String> {
                    ViberBotUpdateEventType.Message.name(),
                    ViberBotUpdateEventType.Delivered.name(),
                    ViberBotUpdateEventType.Seen.name()
                }
            );
        call(ViberBotMethod.SetWebhook, payload);
    }

    public override void unsetWebhook() {
        call(ViberBotMethod.SetWebhook, new ValueMap().set('url', ''));
    }

    protected override HttpRequest prepareRequest(BotMethod method, ValueMap body) {
        HttpRequest request = super.prepareRequest(method, body);
        request.setHeader('X-Viber-Auth-Token', bot.Token__c);
        return request;
    }
}