src/main/default/objects/Bot__c/Bot__c.object-meta.xml
<CustomObject>
    <description>Stores details of a bot instance</description>
    <label>Bot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Bot__c/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <description>Apex class that will be called if the bot receives an update</description>
    <externalId>true</externalId>
    <inlineHelpText>Apex class name</inlineHelpText>
    <label>Handler</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/Bot__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Bot type (e.g. Telegram, WhatsApp)</description>
    <inlineHelpText>Bot type (e.g. Telegram, WhatsApp)</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telegram</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/classes/BotUpdateDispatcher.cls
public class BotUpdateDispatcher {
    public void dispatch(Bot__c bot) {
        handleUpdate(JSON.serialize(bot), bot.Handler__c);
    }

    @Future(callout=true)
    private static void handleUpdate(String jsonBot, String handlerType) {
        Bot__c bot = (Bot__c) JSON.deserialize(jsonBot, Bot__c.class);
        BotService service = new BotServiceFactory().create(bot);
        BotType btType = BotType.valueOf(bot.Type__c);
        Object handler = Type.forName(handlerType).newInstance();
        if (btType == BotType.Telegram) {
            ((ITelegramBotHandler) handler).handle((TelegramBotService) service);
        }
    }
}