force-app/main/default/objects/Bot_Registration__c/Bot_Registration__c.object-meta.xml
<CustomObject>
    <description>Uses to store information about a particular bot registration</description>
    <label>Bot Registration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bot Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bot_Registration__c/fields/System__c.field-meta.xml
<CustomField>
    <fullName>System__c</fullName>
    <description>System of a Bot you want to register for</description>
    <inlineHelpText>System of a Bot you want to register for</inlineHelpText>
    <label>System</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telegram</fullName>
            </value>
            <value>
                <fullName>VK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bot_Setting__mdt/Bot_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Uses to store information about settings for different bots</description>
    <label>Bot Setting</label>
    <pluralLabel>Bot Settings</pluralLabel>
</CustomObject>

force-app/main/default/classes/bot-services/BotService.cls
/**
 * Created by Ilya Matsuev on 8/28/2020.
 */

public with sharing abstract class BotService {

    public Bot_Registration__c registration {get; protected set;}
    public Bot_Setting__mdt botSettings {
        get {
            return BotSettingsService.getBotSettings(registration.System__c);
        }
    }

    public BotService(Bot_Registration__c registration) {
        this.registration = registration.clone(true, false, false, false);
    }


    protected abstract String getEndpoint(String method);

    protected virtual String getEndpoint(String method, Map<String, String> params) {
        return getEndpoint(method) + CalloutHelper.buildUrlParams(params);
    }
}