force-app/main/default/objects/Bot_Registration__c/Bot_Registration__c.object-meta.xml
<CustomObject>
    <description>Uses to store information about a particular bot registration</description>
    <label>Bot Registration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bot Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bot_Registration__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Token uses to identify the bot</description>
    <inlineHelpText>Token uses to identify the bot</inlineHelpText>
    <label>Token</label>
    <length>80</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Bot_Registration__c/fields/WebHook_Path__c.field-meta.xml
<CustomField>
    <fullName>WebHook_Path__c</fullName>
    <description>Path on the org for setting webhooks for a bot</description>
    <inlineHelpText>Path on the org for setting webhooks for a bot</inlineHelpText>
    <label>WebHook Path</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Bot_Setting__mdt/Bot_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Uses to store information about settings for different bots</description>
    <label>Bot Setting</label>
    <pluralLabel>Bot Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Bot_Setting__mdt/fields/API_Url__c.field-meta.xml
<CustomField>
    <fullName>API_Url__c</fullName>
    <label>API Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/registration-resolvers/TelegramWebHookResolver.cls
/**
 * Created by Ilya Matsuev on 8/16/2020.
 */

public with sharing class TelegramWebHookResolver extends WebHookResolver {

    public override Callout setWebHook(Bot_Registration__c registration, Bot_Setting__mdt settings) {
        String params = CalloutHelper.buildUrlParams(new Map<String, String>{
                'url' => CalloutHelper.getRESTUrlStart() + registration.WebHook_Path__c
        });
        String setWebHookCalloutEndpoint = settings.API_Url__c + registration.Token__c + '/setWebhook' + params;
        Callout setWebHookCallout = new Callout(setWebHookCalloutEndpoint, CalloutHelper.METHOD_GET);
        return setWebHookCallout;
    }

    public override Callout resetWebHook(Bot_Registration__c registration, Bot_Setting__mdt settings) {
        String resetWebHookCalloutEndpoint = settings.API_Url__c + registration.Token__c + '/deleteWebhook';
        Callout resetWebHookCallout = new Callout(resetWebHookCalloutEndpoint, CalloutHelper.METHOD_GET);
        return resetWebHookCallout;
    }
}