force-app/main/default/objects/Bot_Registration__c/Bot_Registration__c.object-meta.xml
<CustomObject>
    <description>Uses to store information about a particular bot registration</description>
    <label>Bot Registration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bot Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bot_Registration__c/fields/Hashed_Token__c.field-meta.xml
<CustomField>
    <fullName>Hashed_Token__c</fullName>
    <description>Hash value of a bot token</description>
    <inlineHelpText>Hash value of a bot token</inlineHelpText>
    <label>Hashed Token</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bot_Registration__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Token uses to identify the bot</description>
    <inlineHelpText>Token uses to identify the bot</inlineHelpText>
    <label>Token</label>
    <length>80</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/classes/bot-registration-handlers/BotRegistrationTokenHandler.cls
/**
 * Created by Ilya Matsuev on 8/24/2020.
 */

public with sharing class BotRegistrationTokenHandler implements ITriggerHandler {

    public static final String HASH_ALGORITHM = 'SHA-256';


    public void handle(TriggerContext context, ITriggerService service) {
        List<Bot_Registration__c> registrations = context.newList;
        for (Bot_Registration__c registration: registrations) {
            registration.Hashed_Token__c = getHash(registration.Token__c);
        }
    }

    private String getHash(String text) {
        return EncodingUtil.convertToHex(Crypto.generateDigest(HASH_ALGORITHM, Blob.valueOf(text)));
    }
}