src/main/default/objects/BotSetting__mdt/BotSetting__mdt.object-meta.xml
<CustomObject>
    <description>Stores bot settings</description>
    <label>Bot Setting</label>
    <pluralLabel>Bot Settings</pluralLabel>
</CustomObject>

src/main/default/objects/BotSetting__mdt/fields/ApiUrl__c.field-meta.xml
<CustomField>
    <fullName>ApiUrl__c</fullName>
    <label>API Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

src/main/default/objects/BotSetting__mdt/fields/BaseBotHandler__c.field-meta.xml
<CustomField>
    <fullName>BaseBotHandler__c</fullName>
    <description>The name of the Apex class that implements all specific update events for a bot</description>
    <inlineHelpText>The name of the Apex class that implements all specific update events for a bot</inlineHelpText>
    <label>Base Bot Handler</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/BotSetting__mdt/fields/BotCalloutService__c.field-meta.xml
<CustomField>
    <fullName>BotCalloutService__c</fullName>
    <defaultValue>&quot;BotCalloutService&quot;</defaultValue>
    <description>The name of the class that extends BotCalloutService and configures the way callouts are sent to a bot API</description>
    <inlineHelpText>The name of the class that extends BotCalloutService class</inlineHelpText>
    <label>Bot Callout Service</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/BotSetting__mdt/fields/BotHandlerContext__c.field-meta.xml
<CustomField>
    <fullName>BotHandlerContext__c</fullName>
    <description>The Apex class name that represents the bot context model that will be passed to the handler on the incoming bot updates</description>
    <inlineHelpText>The name of the class that extends BotContext class</inlineHelpText>
    <label>Bot Handler Context</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/BotSetting__mdt/fields/BotService__c.field-meta.xml
<CustomField>
    <fullName>BotService__c</fullName>
    <description>The name of the Apex class that extends BotService class and represents the main functionality of the bot</description>
    <inlineHelpText>The name of the class that extends BotService class</inlineHelpText>
    <label>Bot Service</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/BotSetting__mdt/fields/BotUpdateEvent__c.field-meta.xml
<CustomField>
    <fullName>BotUpdateEvent__c</fullName>
    <description>The Apex class name that represents the payload received from the bot webhook</description>
    <inlineHelpText>The name of the class that implements IBotUpdateEvent interface</inlineHelpText>
    <label>Bot Update Event</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/BotSetting__mdt/fields/BotUpdateResolver__c.field-meta.xml
<CustomField>
    <fullName>BotUpdateResolver__c</fullName>
    <description>The Apex class name that is responsible for resolving the bot record when webhooks are set</description>
    <inlineHelpText>The name of the class that implements IBotUpdateResolver interface</inlineHelpText>
    <label>Bot Update Resolver</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/BotSetting__mdt/fields/BotWebhookService__c.field-meta.xml
<CustomField>
    <fullName>BotWebhookService__c</fullName>
    <description>The name of the class that extends BotWebhookService and configures the way webhooks are set and removed for the bot</description>
    <inlineHelpText>The name of the class that extends BotWebhookService class</inlineHelpText>
    <label>Bot Webhook Service</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/classes/BotSettingsProvider.cls
public class BotSettingsProvider {
    private static final Integer SETTING_QUERY_LIMIT = 50;

    private static final Map<BotType, BotSetting__mdt> settings = new Map<BotType, BotSetting__mdt>();

    private BotSettingsProvider() {}

    static {
        initSettings();
    }

    public static BotSetting__mdt get(BotType type) {
        if (!settings.containsKey(type)) {
            throw new IllegalArgumentException('No setting exists for the ' + type + ' bot type');
        }
        return settings.get(type);
    }

    public static List<BotSetting__mdt> getAll() {
        return settings.values();
    }

    private static void initSettings() {
        List<BotSetting__mdt> allSettings = [
            SELECT
                DeveloperName,
                ApiUrl__c,
                BotService__c,
                BotWebhookService__c,
                BotCalloutService__c,
                BotUpdateResolver__c,
                BotUpdateEvent__c,
                BotHandlerContext__c,
                BaseBotHandler__c
            FROM BotSetting__mdt
            LIMIT :SETTING_QUERY_LIMIT
        ];
        for (BotSetting__mdt setting : allSettings) {
            settings.put(BotType.valueOf(setting.DeveloperName), setting);
        }

        if (Test.isRunningTest()) {
            mock();
        }
    }

    private static void mock() {
        settings.put(
            BotType.Telegram,
            new BotSetting__mdt(
                DeveloperName = BotType.Telegram.name(),
                ApiUrl__c = 'https://tg.bot-api.org/bot',
                BotService__c = 'TelegramBotService',
                BotUpdateEvent__c = 'TelegramUpdateEvent',
                BotHandlerContext__c = 'TelegramBotContext',
                BaseBotHandler__c = 'TelegramBotHandler',
                BotUpdateResolver__c = 'TelegramBotUpdateResolver',
                BotWebhookService__c = 'TelegramBotWebhookService',
                BotCalloutService__c = 'BotCalloutService'
            )
        );
        settings.put(
            BotType.Viber,
            new BotSetting__mdt(
                DeveloperName = BotType.Viber.name(),
                ApiUrl__c = 'https://vb.bot-api.org/bot',
                BotService__c = 'ViberBotService',
                BotUpdateEvent__c = 'ViberUpdateEvent',
                BotHandlerContext__c = 'ViberBotContext',
                BaseBotHandler__c = 'ViberBotHandler',
                BotUpdateResolver__c = 'ViberBotUpdateResolver',
                BotWebhookService__c = 'ViberBotWebhookService',
                BotCalloutService__c = 'ViberBotCalloutService'
            )
        );
    }
}