src/main/default/objects/BotSetting__mdt/BotSetting__mdt.object-meta.xml
<CustomObject>
    <description>Stores bot settings</description>
    <label>Bot Setting</label>
    <pluralLabel>Bot Settings</pluralLabel>
</CustomObject>

src/main/default/objects/BotSetting__mdt/fields/ApiUrl__c.field-meta.xml
<CustomField>
    <fullName>ApiUrl__c</fullName>
    <label>API Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

src/main/default/classes/utils/BotSettingsProvider.cls
public class BotSettingsProvider {
    @TestVisible
    private static final Map<BotType, BotSetting__mdt> settings = new Map<BotType, BotSetting__mdt>();

    private BotSettingsProvider() {}

    public static BotSetting__mdt getSettings(BotType type) {
        if (!settings.containsKey(type)) {
            List<BotSetting__mdt> settingsList = [
                SELECT DeveloperName, ApiUrl__c
                FROM BotSetting__mdt
                WHERE DeveloperName = :type.name()
                LIMIT 1
            ];
            if (settingsList.isEmpty()) {
                throw new IllegalArgumentException('No setting exists for the ' + type + ' bot type');
            }
            settings.put(type, settingsList.get(0));
        }
        return settings.get(type);
    }
}