src/main/default/objects/BotSetting__mdt/BotSetting__mdt.object-meta.xml
<CustomObject>
    <description>Stores bot settings</description>
    <label>Bot Setting</label>
    <pluralLabel>Bot Settings</pluralLabel>
</CustomObject>

src/main/default/objects/BotSetting__mdt/fields/ApiUrl__c.field-meta.xml
<CustomField>
    <fullName>ApiUrl__c</fullName>
    <label>API Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

src/main/default/classes/bot-services/BotSettingsService.cls
public class BotSettingsService {
    private static final Map<String, BotSetting__mdt> settingsBySystemNames = new Map<String, BotSetting__mdt>();

    public static BotSetting__mdt getBotSettings(String systemName) {
        BotSetting__mdt settings = null;
        if (settingsBySystemNames.containsKey(systemName)) {
            settings = settingsBySystemNames.get(systemName);
        } else {
            List<BotSetting__mdt> settingsList = [
                SELECT DeveloperName, ApiUrl__c
                FROM BotSetting__mdt
                WHERE DeveloperName = :systemName
            ];
            if (!settingsList.isEmpty()) {
                settings = settingsList.get(0);
                settingsBySystemNames.put(systemName, settings);
            }
        }
        return settings;
    }
}