src/main/default/objects/Bot_Registration__c/Bot_Registration__c.object-meta.xml
<CustomObject>
    <description>Uses to store information about a particular bot registration</description>
    <label>Bot Registration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bot Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Bot_Registration__c/fields/Hashed_Token__c.field-meta.xml
<CustomField>
    <fullName>Hashed_Token__c</fullName>
    <description>Hash value of a bot token</description>
    <inlineHelpText>Hash value of a bot token</inlineHelpText>
    <label>Hashed Token</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Bot_Registration__c/fields/WebHook_Path__c.field-meta.xml
<CustomField>
    <fullName>WebHook_Path__c</fullName>
    <description>Path on the org for setting webhooks for a bot</description>
    <inlineHelpText>Path on the org for setting webhooks for a bot</inlineHelpText>
    <label>WebHook Path</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/classes/registration-resolvers/TelegramWebHookResolver.cls
/**
 * Created by Ilya Matsuev on 8/16/2020.
 */

public with sharing class TelegramWebHookResolver extends WebHookResolver {
    public override Callout setWebHook(Bot_Registration__c registration) {
        TelegramBotService botService = new TelegramBotService(registration);
        return botService.setWebHook(
            CalloutHelper.getRESTUrlStart() +
            registration.WebHook_Path__c +
            CalloutHelper.SLASH +
            registration.Hashed_Token__c
        );
    }

    public override Callout resetWebHook(Bot_Registration__c registration) {
        TelegramBotService botService = new TelegramBotService(registration);
        return botService.deleteWebHook();
    }
}